fix SetGroupVersionKind function not work in kv,vm,vmi etc list inter…
kubevirt/kubevirt pull request #10233
Opened 2023-08-03 13:02 UTC by HHHskkk

…face

**What this PR does / why we need it**:

when I use the vm list interface to get vmlist, in items apiVersion is v1alpha3.
if vm list interface, SetGroupVersionKind func used to set apiVersion to v1，but it not works because a incorrect use golang for range.

same in Kv、Migration、Replicaset、Vmi List interface.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2023-08-04 06:36 UTC, rmohr commented
/test all

2023-08-08 12:27 UTC, lyarwood requested changes
Would you mind adding some basic unit test coverage for this?

2023-08-10 06:50 UTC, HHHskkk commented
> Would you mind adding some basic unit test coverage for this?

no problem. ut already added.

2023-08-10 06:51 UTC, HHHskkk commented
/retest

2023-08-10 08:18 UTC, lyarwood approved these changes
/lgtm

Thanks!

2023-08-10 08:19 UTC, lyarwood commented
/ok-to-test

2023-08-10 09:02 UTC, lyarwood commented
/lgtm cancel

Looks like you need to run `make generate` before committing the changes, apologies for missing this!

2023-08-29 03:37 UTC, HHHskkk commented
make generate done!

2023-08-29 06:15 UTC, HHHskkk commented
/retest

2023-08-29 09:34 UTC, HHHskkk commented
/test pull-kubevirt-e2e-k8s-1.28-sig-storage

2023-08-29 09:34 UTC, HHHskkk commented
/test pull-kubevirt-e2e-k8s-1.28-sig-storage

2023-08-29 10:02 UTC, lyarwood commented
/lgtm
/retest-required

2023-08-30 07:58 UTC, xpivarc reviewed
/approve

2023-08-30 07:59 UTC, xpivarc commented
/?

2023-08-30 13:56 UTC, brianmcarey commented
/test pull-kubevirt-fossa

2023-08-30 21:27 UTC, merged