Add a notice to virtctl console about logs
kubevirt/kubevirt pull request #10917
Opened 2023-12-21 11:16 UTC by tiraboschi

**What this PR does / why we need it**:
Guest serial console output can now be streamed
to cluster logs. This could be eventually enabled
at cluster level being not so visible to VM owners. Those logs include the boot logs but also the output of an interactive usage of the first serial console. No access passwords for the console nor
properly handled passwords (not echoed to the screen) are going to be collected n the logs.
However, if the VM user types a password by mistake instead of a command name or if the password is visible on the screen as a clear text parameter or in the
output of any command, it could be streamed
to cluster logs along with all other screen visible text.

Let's have `virtctl console` emitting a notice
(if LogSerialConsole is not explicitly disabled) for the user suggesting to use SSH when handling sensitive informations.

Adding a test covering `virtctl console` output.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [X] PR: The PR description is expressive enough and will help future contributors
- [X] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [X] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Add a notice to virtctl console about logs
```

2023-12-21 13:40 UTC, tiraboschi commented
/retest

2024-01-02 10:44 UTC, tiraboschi commented
/hold

2024-01-03 15:24 UTC, aburdenthehand commented
/cc @nunnatsa

2024-01-03 15:34 UTC, xpivarc requested changes

2024-01-03 15:34 UTC, xpivarc commented on pkg/virtctl/console/console.go
> +	k8smetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
nit: We use metav1

2024-01-03 15:34 UTC, xpivarc commented on pkg/virtctl/console/console.go
> +	logWarning := "Caution: the output of this console connection can be streamed into system logs.\nIf you are inputting any screen visible sensitive information please consider using SSH unless the se
nit: const
and just add it conditionally at line 132.

2024-01-03 15:34 UTC, xpivarc commented on tests/virtctl/console.go
> +			Entry("without LogSerialConsole", nil, true),
Do we need 3 functional tests?

2024-01-03 15:34 UTC, xpivarc commented on tests/virtctl/console.go
> +var _ = Describe("[sig-compute][virtctl]console", decorators.SigCompute, func() {
I believe this is "unit-testable". Can we work on making this unit test only?

2024-01-09 14:45 UTC, tiraboschi commented
Closing: after debating it, we decided to close this since every virtualization system (excluding confidential computing ones) is potentially exposed and so the warning is pointless.

2024-01-09 14:45 UTC, closed without merging