Expose static ip property when generating Multus annotation
kubevirt/kubevirt pull request #10923
Opened 2023-12-24 01:02 UTC by chomatdam

**What this PR does / why we need it**:
When generating the Multus network annotation from the VMI spec, 3 properties are bubbling up:
- `networkName`
- `namespace`
- `interface`

This PR is exposing a tad more of the Multus contract with `ips` enabling folks to define static IPs for their VMs.

**Which issue(s) this PR fixes**:
Fixes #4564

**Special notes for your reviewer**:
- This PR is applying a change to the OpenAPI spec by exposing an `ips` field next to `networkName` when defining a Multus network, I would need guidance regarding the code generation workflow for this spec (currently just edited the go object and YAML spec).

**Checklist**
- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or **not required**
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
VMI spec enhanced with ips field to enable static IP assignment for VMs using Multus network.
```

2023-12-24 13:40 UTC, EdDev requested changes
Thank you for the contribution.

The suggestion here is to add IPAM definition through the VM/VMI API.

I do not think there is an agreement to enter the IPAM domain in Kubevirt.
You could raise this as an enhancement through a design proposal [1] or just join the weekly community meeting [2] and open a discussion about it.

I do not see Kubevirt going in this direction, because we are not in the business of managing IP addresses to VM NICs. Kubevirt in this regard depends on the network provider to manage this for the primary network and suggests to avoid using IPAM for secondary networks (for pods).

[1] https://github.com/kubevirt/community/tree/main/design-proposals
[2] https://github.com/kubevirt/kubevirt#community

2023-12-24 17:45 UTC, chomatdam commented
Hi Edward,

Thank you for taking a look at it. I will expand more on the context, current limitations, and the scope of the change.

**Context**

We are working in a setup where we deploy containers (pod + Multus networks) and VMs isolated from the pod network (Multus network as default). 
Users connect to these VMs with a jump box (VNC/ssh/...) and are not aware of the pod network. Leveraging the Multus service project, similar to kube-proxy, we have a multus-proxy routing the traffic from the Kubernetes Service network to the Multus network (Pod IP).

**Limitations**
- when a static IP is desired, by having Multus as the default network (existing feature), to make the VM reachable from a Kubernetes service, there is a need for alignment between the pod IP (on Multus network) and the network interface inside the VM configured through cloud-init/sysprep

**Scope**
- Control over VMI's Pod IP when Multus is the default network

**Implementation proposals**

Regarding the implementation, this [NetworkSelectionElement](https://github.com/k8snetworkplumbingwg/multus-cni/blob/acfbd42719545844248ecc35cc93d0ce367f87e5/pkg/types/types.go#L128) is the Multus spec for the pod annotation generated by KubeVirt CR [here](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/multus_annotations.go#L63).

- (Current) An extra field is explicitly exposed for the pod IP when generating the Multus pod annotation
- Multus spec _MAY_ change in the future, KubeVirt team doesn't want to expand and maintain this contract and prefers something more flexible, similar to what Kafka does, a pass-through map, that folks can leverage to pass their Multus properties
- KubeVirt wants to keep basic support for Multus, pod IP stays dynamic and focuses only on IPAM inside the VM, a documentation update would mention the limitation and encourage to patch on their end the pod annotation or override it, trying to reproduce what KubeVirt does when resolving the interface name to put in the pod annotation.

Let me know your thoughts and I'll be happy to submit any update (code/doc/design proposal) 🙂

2023-12-31 02:46 UTC, chomatdam commented
Hi @EdDev,

I'm quite new to the KubeVirt and Multus world 🙂, after a few tests this week this would be my recap:

### Default network
A default Multus network can't have its IP configured, it's the default network annotation generating [an extra network](https://github.com/k8snetworkplumbingwg/multus-cni/blob/acfbd42719545844248ecc35cc93d0ce367f87e5/pkg/k8sclient/k8sclient.go#L203). I totally join you on what you said and understand now better it's the CNI's responsibility to manage the default network fully.

### Secondary networks (with Multus)
Regarding the PR itself, just to mention it, it has been deployed and it's working.

Regarding whether it's an acceptable enhancement, I think as soon as the `multus` field for the `network` object appears in the VMI spec, KubeVirt is supporting Multus, is not responsible for how Multus can be configured but simply could be a pass-through for any existing configurable Multus property.

I'm not sure how it will evolve in the future (network binding plugin for Multus and current `multus` field deprecated?) but I think in the current state, adding `ips` would be the minimum (at least for my use case) but this field could also be added to a new map for any Multus property the end-user may need.

Just in case you want to hear more about the use case, if you have recommendations on a better "how" reaching the end goal, basically, my use case is reproducible environments for students where secondary networks have static IPs to provide the same documentation (same IPs) and also validate what they are doing through consistent system events.

Looking forward to hearing back, as a beginner KubeVirt user, overall the KubeVirt code base is very impressive, a bit intimidating, I think detailed documentation around how to build the project would be very useful, for example:
- Scenario 1: I want to build everything
- Scenario 2: I want to build a specific component (e.g. `virt-controller`)
- Scenario 3: I'm doing an API change and need to regenerate
- "Issues you may encounter": cache issue, mac user being on aarch64 and wanting x86_64/amd64 binary

2023-12-31 17:11 UTC, chomatdam commented
As YAML, proposals would look like:

```yaml
# 1) Only IP property
networks:
  multus:
    networkName: namespace/my-multus-network
    default: false
    ips: ["10.10.0.5"]
```

```yaml
# 2) Map of Multus request properties (validation on keys as an option)
networks:
  multus:
    networkName: namespace/my-multus-network
    default: false
    request-properties:
      ips: ["10.10.0.5"]
      [...]
```

```yaml
# 3) Flat hierarchy with all the available Multus request properties
networks:
  multus:
    networkName: "namespace/my-multus-network"
    default: false
    ips:
      - "10.10.0.5"
      - "10.10.0.5/24"
    mac: "c2:11:22:33:44:66"
    infiniband-guid: "24:8a:07:03:00:8d:ae:2e"
    interface: "enp1s0"
    portMappings:
      - hostPort: 8080
        containerPort: 80
        protocol: "tcp"
        hostIp: "10.0.0.1"
    bandwidth:
      - ingressRate: 100
        ingressBurst: 200
        egressRate: 100
        egressBurst: 200
    deviceId: "dev0"
    cniArgs:
      key1: "value1"
    defaultRoutes:
      - "10.1.1.1"
      - "fc00::1"
```

**NOTE:** `name` and `namespace` are already being implemented through `networkName` (e.g. `ns/network`), avoiding any breaking change around that.

2024-01-01 11:16 UTC, EdDev commented
@chomatdam , thank you for all the details, it puts everything in context.

While I understand the need to manage IP addresses, I think we should aim to accomplish the same without embedding this into the virtualization management system.
The cost of owning the IP management is high and is non existent at the moment. Although it may seem that this can somehow be offloaded to Multus, it is unlikely to be enough.
The fact that the desired state includes an IP, will require Kubevirt to do whatever is needed for the IP to appear in the guest (and not only on the pod). It will also require validations that the IP is not duplicated and to assure network providers and different IPAM vendors work correctly with Kubevirt.

Also, Kubevirt API is an abstraction over various backend APIs, including Multus.
Kubevirt is not exposing all libvirt, qemu, multus, etc APIs intentionally. It tries to expose a more abstract API that fits most cases. The areas that are not covered are sometimes available through hooks (e.g. sidecar hooks and newer network binding plugins), or through downstream forks that will patch Kubevirt for their specific needs.

IMO you could accomplish your goals without Kubevirt exposing and owning all of Multus parameters, especially the IP ones.
Here some options that I can think of:
- Let the IP to be assigned dynamically and based on the IP assigned, configure the rest: Services, Guest configuration. As the service IP is the one exposed to users, the actual IP assigned to pods/VMs does not have to be static.
- Manage the secondary networks IPAM with an external system, same as you would do with bare metal nodes. E.g. you could assign static IPs through cloud-init when defining the VM manifest. In this case, the virtualization system will not be aware of IPAM.

I know there is work being done on sticky IPs, which is somewhere in the middle of all this. I.e. when a VM is started, it will preserve its IP even if shutdown and started later. @maiqueb was leading that effort.
For clarification, Kubevirt is still not involved in managing IPs.

I can share that we do manage mac addresses, to assure mac collision will not occur by integrating with the [KMP](https://github.com/k8snetworkplumbingwg/kubemacpool) project. But we did not embed it into Kubevirt logic. KMP is not simple, it had some major bumps in its history and even today it is questionable if the strategy is worth the cost. IP management to me sounds much more complex, and therefore my reservation.

I am just one voice, others may have other views on this subject.

2024-01-11 11:52 UTC, EdDev commented
I can think of one option to integrate extended multus options without Kubevirt involvement.

- Annotate the VM/VMI with the needed information.
- Create and run a mutating webhook for pods. This webhook will interpret the VMI annotation and patch the pod multus annotation with the needed additions.

At its base, this webhook logic will need to:
- Identify the VMI that manages the pod.
- Interpret the annotation from the VMI.
- Mutate the pod multus annotation with the needed data.
- Assure this is working also for pod update or patching (creation is not enough).

2024-01-25 20:32 UTC, chomatdam commented
Hi @EdDev,

I'm still planning to work on it at some point 🙂, quick question on the approach, you are recommending going with a webhook instead of the `virt-controller` applying at pod creation the logic below:
- if a multus annotation already exists on the VMI, apply it and append the resolved interface name

Do you have details on the advantages of doing it as a webhook observing create/update/patch? or the `virt-controller` way is also an acceptable approach?

Thanks!

2024-01-26 11:34 UTC, maiqueb commented
AFAIU, the advantage is you get to do this out of the kubevirt tree, according to your requirements, without needing KubeVirt maintainers to actively maintain your proposal.

Implementing your use-case in a generic way is of course preferable, which means the API (which annotation will the webhook look for) should have some agreement.

I encourage you to attend the KubeVirt community meeting and present there a proposal for this. If you come up with a design proposal for it, I'm sure people in the network sig would gladly review it.

2024-01-26 17:57 UTC, chomatdam commented
Sounds good - I'll try to be there next Wednesday!

If I try to capture the gist of it:
- guest level having the ownership over IPAM
- customizing the Multus configuration through its annotation is not part of the 80-90% use cases
- integrating it as a webhook to physically, in the code, keep this specific use case apart from the main tree or by not being there, avoiding inviting people to customize this annotation, losing control over the expected behavior, and getting a significant amount of issues related to the KubeVirt-Multus relationship
- webhook potentially with a feature gate, feature disabled by default to have the end-user wanting it, accepting that they are signing for community on-your-own/on-the-side feature? 🙂

2024-01-28 12:51 UTC, EdDev commented
Answering myself here so I will not forget.

> I can think of one option to integrate extended multus options without Kubevirt involvement.
> 
>     * Annotate the VM/VMI with the needed information.
> 
>     * Create and run a mutating webhook for pods. This webhook will interpret the VMI annotation and patch the pod multus annotation with the needed additions.

It is not nice for the pod webhook to query a different object (the VMI).
I think that by default, most annotations on the VMI are passed to the pod as is, so we can assume
that the annotation on the VM/VMI will be reflected on the pod as well.
(then we do not need to query the VMI in the webhook)
 
> At its base, this webhook logic will need to:
> 
>     * Identify the VMI that manages the pod

This will not be needed if the annotation reached the pod.

> 
>     * Interpret the annotation from the VMI.
> 
>     * Mutate the pod multus annotation with the needed data.
> 
>     * Assure this is working also for pod update or patching (creation is not enough).

> customizing the Multus configuration through its annotation is not part of the 80-90% use cases

At the moment, this is the only scenario which requires this, so I would say it is 98% :)

We do plan to support passing arbitrary data as key-value through the `cni-args`field, but this is for allowing the information to pass from the network annotation on the pod to the CNI plugin itself, which is not the same.

> webhook potentially with a feature gate, feature disabled by default to have the end-user wanting it, accepting that they are signing for community on-your-own/on-the-side feature?

I do not see a need for a FG here. The deployment of a webhook is controller by the cluster-admin, there is no need to protect it beyond that. But maybe I do not understand what it protects exactly.

Looking forward to see a design proposal with details on how this can be implemented.

2024-03-02 00:07 UTC, chomatdam commented
Hi @EdDev,

I finally got some time to look more into what you suggested 🙂 

My initial approach is still in the git history if we are changing our minds:
1. [controller] exposing `ips` or Multus contract
2. [controller] letting a Multus annotation flow at creation from the VMI to the pod and only appending to it computed or missing fields as the interface name, or a mac address set by the user in the VMI spec

For the [pod webhook approach](https://github.com/kubevirt/kubevirt/blob/04de5b32e0723c135c7acbf029ca1ac590f80b95/pkg/virt-api/webhooks/mutating-webhook/mutators/virt-launcher-pod-mutator.go#L26), it's a bit more involved, I would like to do a sanity check with you before the last mile. The same logic as the existing in the controller would have to be reused to pull data from the VMI to resolve/compute values for:
- interface name (from `CreateHashedNetworkNameScheme(vmiNetworks)`)
- mac address (VMI spec: `interface.*.macAddress`)

Let me know what are your thoughts. If it's what you pictured, or if it's off, and about the need for the VMI object to get at least these 2 values above in the annotation.

2024-03-03 06:49 UTC, EdDev commented
> For the [pod webhook approach](https://github.com/kubevirt/kubevirt/blob/04de5b32e0723c135c7acbf029ca1ac590f80b95/pkg/virt-api/webhooks/mutating-webhook/mutators/virt-launcher-pod-mutator.go#L26) (link to draft code), it's a bit more involved, I would like to do a sanity check with you before the last mile. The same logic as the existing in the controller would have to be reused to pull data from the VMI to resolve/compute values for:
> 
>     * interface name (from `CreateHashedNetworkNameScheme(vmiNetworks)`)
> 
>     * mac address (VMI spec: `interface.*.macAddress`)
> 
> 
> Let me know what are your thoughts. If it's what you pictured, or if it's off, and confirming about the need to source from the VMI object to get at least these 2 values above in the annotation.

Based on [this](https://github.com/kubevirt/kubevirt/pull/10923#issuecomment-1913586112) comment, the best approach would be to annotate in advance the VM/VMI with the required information. Instead of fetching the VMI object from within the webhook.
When the pod is created, the multus annotation is already there so you could identify which interface you want to add to information, and the exact information could be added as an annotation to the VM/VMI.

But all this needs to be checked.
There is a need to identify the relevant interface somehow, there is a need to check if VM annotations traverses to the VMI and pod, etc.

2024-03-03 22:19 UTC, chomatdam commented
gotcha, I started to be confused between the different scenarios! So I've been validating the assumptions:
- VM annotations are not forwarded to the VMI
- VMI annotations are forwarded to the pod
-  if the VMI has `k8s.v1.cni.cncf.io/networks`, it will be overridden by what the virt-controller generates for this annotation key

so basically, it's about picking a key for the pod annotation to read from, and when applicable, the webhook would merge these values into `k8s.v1.cni.cncf.io/networks` with what it gets from this other annotation

I'll move forward in the implementation tomorrow 🙂

2024-03-06 01:41 UTC, chomatdam commented
It's ready for review @EdDev 🙂 - my only question would be regarding the naming, having side-by-side
- `k8s.v1.cni.cncf.io/networks`
- `k8s.v1.cni.cncf.io/networks-customization` _(new)_

If you prefer this "consistent style" or something more KubeVirt-related being a VMI annotation as `kubevirt.io/networks-customization` or `kubevirt.io/multus-customization`

2024-03-06 05:27 UTC, chomatdam commented
Just updated [the documentation](https://github.com/kubevirt/user-guide/blob/0c4eeb90f6d867323dfc3a8d502841cbf897a91c/docs/virtual_machines/interfaces_and_networks.md#customizing-the-multus-pod-annotation) for it (https://github.com/kubevirt/user-guide/pull/749).

2024-03-12 18:35 UTC, chomatdam commented
[Design proposal](https://github.com/kubevirt/community/blob/01e897a137c90f5c020f04b4eb3535d288e86331/design-proposals/multus-annotation-customization.md) added ([community/pull/275](https://github.com/kubevirt/community/pull/275))

2024-06-11 07:13 UTC, maiqueb commented
/uncc

2024-08-10 07:51 UTC, closed without merging

2024-11-23 17:59 UTC, kfox1111 commented
I need this.... What is the current status?