virt-op deployments: use k8s's pointer
kubevirt/kubevirt pull request #10954
Opened 2024-01-02 06:40 UTC by dankenigsberg

We already use 3 libraries for the same thing, there is no need to keep a module-local version, too.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

2024-01-02 09:50 UTC, xpivarc reviewed
/approve

2024-01-03 09:33 UTC, fossedihelm approved these changes
Sometime in the future we should chose between k8s's pointer package or
our more **generic** package(https://github.com/kubevirt/kubevirt/blob/main/pkg/pointer/pointer.go) 
:)

2024-01-03 09:47 UTC, dankenigsberg commented
> Sometime in the future we should chose between k8s's pointer package or our more **generic** package(https://github.com/kubevirt/kubevirt/blob/main/pkg/pointer/pointer.go) :)

+1

Nowadays, k8s has its own generic package and we already use it https://github.com/kubevirt/kubevirt/blob/main/vendor/k8s.io/utils/ptr/ptr.go#L50

2024-01-03 10:02 UTC, fossedihelm commented
/lgtm

2024-01-03 16:36 UTC, EdDev requested changes

2024-01-03 16:36 UTC, EdDev commented on pkg/virt-operator/resource/generate/components/daemonsets.go
> +				Privileged: pointer.Bool(true),
I do not think we should encourage using this one.
Either use the k8s `ptr` one or the in-house `pointer` one.

2024-01-03 16:38 UTC, EdDev commented
Ahh... well, it is not worth blocking on this... it is better than keeping a local version.

/lgtm

2024-01-03 16:41 UTC, EdDev commented
> Nowadays, k8s has its own generic package and we already use it https://github.com/kubevirt/kubevirt/blob/main/vendor/k8s.io/utils/ptr/ptr.go#L50

Well, I do do not like that much the k8s package. It has things we do not use, some are very specific and I see no reason to depend on it. In practice, they can potentially break it and we'll need to adjust all over the project.

For simple things, I would just create a local version and continue with it.

2024-01-03 22:09 UTC, merged