tests/storage: remove newVMIWithEphemeralPVC()
kubevirt/kubevirt pull request #11537
Opened 2024-03-18 17:36 UTC by assafad

### What this PR does
Remove newVMIWithEphemeralPVC() function in `tests/storage/storage.go`, and use  instead:
```
vmi = libvmi.New(
	libvmi.WithResourceMemory("1Mi"),
	libvmi.WithEphemeralPersistentVolumeClaim(),
         )
```

/sig code-quality

### Release note

```release-note
None
```

2024-03-18 19:59 UTC, dankenigsberg requested changes

2024-03-18 19:59 UTC, dankenigsberg commented on tests/storage/storage.go
> +					libvmi.WithNamespace(testsuite.GetTestNamespace(nil)),
```suggestion
```
I think that it's not required. `RunVMIAndExpectLaunch` does the same thing.

2024-03-18 19:59 UTC, dankenigsberg commented on tests/storage/storage.go
> +					libvmi.WithResourceMemory("256Mi"),
how about using `NewGuestless` ? I don't think that the test needs anything to run inside the VM.

2024-03-18 21:40 UTC, assafad commented
/retest

2024-03-19 06:28 UTC, fossedihelm commented
Please, adjust the PR description to match the changes that come from the comments.
Thanks
/lgtm

2024-03-19 09:09 UTC, enp0s3 reviewed
/approve

2024-03-19 09:45 UTC, arnongilboa commented
/lgtm

2024-03-19 12:37 UTC, assafad commented
@arnongilboa, @akalenyu Hi, looks like this changes are failing the storage lane. I'm not sure why, can you please help identify the issue?

2024-03-19 12:42 UTC, dankenigsberg commented
>  Hi, looks like these changes are failing the storage lane. I'm not sure why, can you please help identify the issue?
Can you be more specific? Which test(s) are failing? How?

2024-03-19 12:51 UTC, assafad commented
> > Hi, looks like these changes are failing the storage lane. I'm not sure why, can you please help identify the issue?
> > Can you be more specific? Which test(s) are failing? How?

Sure, basically I see one recurring failure in CI:
```[sig-storage] Storage Starting a VirtualMachineInstance [rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]With ephemeral alpine PVC [test_id:3137]should not persist data expand_less	21s
{ Failure tests/storage/storage.go:459
Expected success, but got an error:
    <*kubecli.AsyncSubresourceError | 0xc006a39710>: 
    Can't connect to websocket (401): websocket: bad handshake
    
    {
        err: "Can't connect to websocket (401): websocket: bad handshake\n",
        StatusCode: 401,
    }
tests/storage/storage.go:474}
```
So, it's failing in https://github.com/kubevirt/kubevirt/blob/171adabb282c1eee81e7daaa5f09aa4d1e79ea3e/tests/storage/storage.go#L474

Perhaps I'm missing something when configuring the VMI beforehand in https://github.com/kubevirt/kubevirt/blob/171adabb282c1eee81e7daaa5f09aa4d1e79ea3e/tests/storage/storage.go#L460-L463

2024-03-19 18:16 UTC, assafad commented
> It seems like there is no 1:1 equivalence between the VMI created before and after this PR. If I read correctly the diff is
> 
> ```
> libvmi.WithInterface(libvmi.InterfaceDeviceWithMasqueradeBinding()),
> libvmi.WithNetwork(v1.DefaultPodNetwork()),
> ```
> 
> @AlonaKaplan are these ^ required for console access?

@akalenyu I added those, but looks like the same test is still failing.

2024-03-19 18:22 UTC, assafad commented
> It seems like there is no 1:1 equivalence between the VMI created before and after this PR. If I read correctly the diff is
> 
> ```
> libvmi.WithInterface(libvmi.InterfaceDeviceWithMasqueradeBinding()),
> libvmi.WithNetwork(v1.DefaultPodNetwork()),
> ```
> 
> @AlonaKaplan are these ^ required for console access?

The issue persist also after adding these.

2024-03-20 12:21 UTC, akalenyu commented
> > It seems like there is no 1:1 equivalence between the VMI created before and after this PR. If I read correctly the diff is
> > ```
> > libvmi.WithInterface(libvmi.InterfaceDeviceWithMasqueradeBinding()),
> > libvmi.WithNetwork(v1.DefaultPodNetwork()),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @AlonaKaplan are these ^ required for console access?
> 
> The issue persists also after adding these.

Interesting, so the VM before and after this PR is identical in this test, but the test still fails? Does it fail locally?

2024-03-20 17:55 UTC, assafad commented
@akalenyu Sorry, they weren't identical, I was missing namespace when [defining the VMI](https://github.com/kubevirt/kubevirt/compare/475f6ba29a9aeb8b17c062b98c4c054c254fc4e8..bec33943cdd1f4110e259547cbd8a158047951f6), as it was done by `tests.NewRandomVMI()`. Now it passes locally.

2024-03-23 15:33 UTC, dankenigsberg approved these changes

2024-03-23 20:56 UTC, AlonaKaplan commented
> libvmi.WithInterface(libvmi.InterfaceDeviceWithMasqueradeBinding()),
> libvmi.WithNetwork(v1.DefaultPodNetwork()),
> ```
> 
> @AlonaKaplan are these ^ required for console access?

No it is not required.
If you don't specify the network and the interface, the default bridge binding will be used.
It doesn't matter for the console to work which bindibg is used, even if the VM has no interfaces at all, the console should work.

2024-03-23 22:53 UTC, merged