Consolidate node-labeller's labels usage
kubevirt/kubevirt pull request #11645
Opened 2024-04-03 17:49 UTC by xpivarc

### What this PR does
Use well defined constants for labels.

Fixes #

### Special notes for your reviewer

### Release note

```release-note
NONE
```

2024-04-04 07:18 UTC, EdDev approved these changes

2024-04-05 06:33 UTC, fossedihelm requested changes

2024-04-05 06:33 UTC, fossedihelm commented on tests/libnode/node.go
> +				cpu := strings.TrimPrefix(key, v1.HostModelCPULabel)
```suggestion
			if strings.Contains(key, v1.CPUModelLabel) {
				cpu := strings.TrimPrefix(key, v1.CPUModelLabel)
```

2024-04-15 13:09 UTC, xpivarc commented
@alicefr @fossedihelm PTAL

2024-04-15 13:13 UTC, fossedihelm approved these changes

2024-04-15 13:16 UTC, alicefr commented
@xpivarc looks good
/approve

2024-04-16 00:34 UTC, merged