Fixed leaked storage classes in tier 1 storage tests
kubevirt/kubevirt pull request #11782
Opened 2024-04-24 10:33 UTC by EduardGomezEscandell

### What this PR does
Before this PR: Some storage tier 1 tests would create storage classes and never remove them
After this PR: No storage classes are leaked from tests

Fixes [CNV-38887](https://issues.redhat.com/browse/CNV-38887)

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place:  [CNV-38887](https://issues.redhat.com/browse/CNV-38887)

### Special notes for your reviewer

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

2024-04-24 10:38 UTC, EduardGomezEscandell commented on tests/storage/datavolume.go
> +			Expect(stderror.Join(
I wanted to ensure the second function runs even if the first one fails.

I'm new to gomega so I'm not sure the assertion failure causes the function to exit.

2024-04-24 13:23 UTC, EduardGomezEscandell commented
/test pull-kubevirt-e2e-k8s-1.29-sig-storage pull-kubevirt-e2e-k8s-1.28-sig-storage pull-kubevirt-e2e-k8s-1.27-sig-storage

2024-04-24 14:01 UTC, mhenriks commented
/test pull-kubevirt-e2e-k8s-1.29-sig-storage pull-kubevirt-e2e-k8s-1.28-sig-storage pull-kubevirt-e2e-k8s-1.27-sig-storage

2024-04-24 15:09 UTC, xpivarc commented on tests/storage/datavolume.go
> +			Expect(stderror.Join(
It doesn't matter because if the first one fails we are already not in good shape.

2024-04-24 15:09 UTC, xpivarc reviewed
/approve

2024-04-25 14:13 UTC, EduardGomezEscandell commented
/test pull-kubevirt-e2e-k8s-1.29-sig-storage pull-kubevirt-e2e-k8s-1.28-sig-storage pull-kubevirt-e2e-k8s-1.27-sig-storage

2024-04-25 15:32 UTC, mhenriks commented
/lgtm

2024-04-26 04:54 UTC, EdDev requested changes
I think there are a few issues here:
- The cleanup is not assured if the prev delete fails. It will be better to place the new one in a separate AfterEach. It will be nicer IMO to use `DeferCleanup` after it is created.
- Why this is not part of the general cleanup we do after each test?
- The deletion is async, i.e. when the next test starts, it may yet to be gone. Can this cause a problem or is it ok?
- To keep the history of commits clean, it will be better to squash the two commits. Initial I did not understand what is going on.

2024-04-26 10:29 UTC, EdDev commented on tests/storage/datavolume.go
> +	FContext("With VirtualMachinePreference and PreferredStorageClassName", func() {
Leftover

2024-04-26 10:43 UTC, EduardGomezEscandell commented on tests/storage/datavolume.go
> +	FContext("With VirtualMachinePreference and PreferredStorageClassName", func() {
Woops, good catch

2024-04-26 10:56 UTC, EdDev approved these changes
Thanks!

2024-04-27 07:52 UTC, merged

2024-05-02 10:38 UTC, EduardGomezEscandell commented
/cherrypick release-1.2