acpiIndex support for hostDev interfaces
kubevirt/kubevirt pull request #12108
Opened 2024-06-12 15:37 UTC by nikhil7sharma

acpiIndex support for hostDev interfaces to pass xml with acpiIndex information to libvirt.
As of today, it is supported for v1.,Interfaces only.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

2024-06-12 15:56 UTC, ian-howell approved these changes

2024-06-13 04:43 UTC, nikhil7sharma commented
/release-note-none

2024-06-13 06:00 UTC, nikhil7sharma commented
/test all

2024-06-14 12:52 UTC, alicefr commented
@nikhil7sharma can you please add some unit tests? Additionally, I would squash the 2 commits into a single one
/cc @EdDev

2024-06-16 05:00 UTC, EdDev requested changes
This seems to be only an API change without a backend that actually supports it.

I suggest to review the original network PR [1] which implemented it.

[1] https://github.com/kubevirt/kubevirt/pull/9116

2024-06-17 19:23 UTC, nikhil7sharma commented
> This seems to be only an API change without a backend that actually supports it.
> 
> I suggest to review the original network PR [1] which implemented it.
> 
> [1] #9116

Thanks @EdDev . Yes, I had gone though the original changes for acpiIndex introductions. You are right that, there is only API change (and no backend change) and hence swagger.json is updated with doc file changes.
 In the original commit, it was taken care for v1.Interfaces, which are passed to libvirt via XML but "hostDevices" was missed. And, so to cover up, this minor changes is done.
So, please help to review.

2024-06-17 19:44 UTC, nikhil7sharma commented
> @nikhil7sharma can you please add some unit tests? Additionally, I would squash the 2 commits into a single one /cc @EdDev

Thanks @alicefr. Attached is the unit test, functional test log in kind cluster.
[KubeVirt Test logs.pdf](https://github.com/user-attachments/files/15876404/KubeVirt.Test.logs.pdf)

2024-06-17 20:08 UTC, EdDev commented
> You are right that, there is only API change (and no backend change) and hence swagger.json is updated with doc file changes.

API changes are not enough to make it work.
I do not understand what you tested to confirm it works.

You will need to show it works through e2e tests or unit tests. They need to be included in this PR and ran on CI so we can see it.

2024-10-23 20:01 UTC, jean-edouard commented
/hold
@nikhil7sharma please actually implement the API and write tests, thank you!

2024-11-22 20:58 UTC, closed without merging