Add v1.3.0 perf and scale benchmarks data
kubevirt/kubevirt pull request #12247
Opened 2024-06-28 13:36 UTC by Sreeja1725

### What this PR does
Before this PR:
There is no doc for v1.3 
After this PR:
This PR adds  perf and benchmarks data doc for v1.3 release.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Add perf-scale benchmarks for release v1.3
```

2024-06-28 13:47 UTC, alaypatel07 requested changes
couple of nits, overall looks good

cc @xpivarc @rthallisey for reviews

2024-06-28 13:47 UTC, alaypatel07 commented on docs/perf-scale-benchmarks.md
>  #### Performance benchmarks for v1.2.0 release
s/v.1.2.0/v.1.3.0/g

2024-06-28 14:13 UTC, Sreeja1725 commented on docs/perf-scale-benchmarks.md
> +1. The violet dotted line in the graph is March 25, 2024, denoting change in k8s provider from v1.27 to v1.29.
Added

2024-06-28 14:50 UTC, alaypatel07 commented on docs/perf-scale-benchmarks.md
> +NOTE: The scalability metrics were hampered by a bug, that was fixed before the release [https://github.com//pull/12096]. Hence the scalability metrics data needs to be re-evaluated by users with the
broken link

2024-06-28 15:11 UTC, alaypatel07 commented
/lgtm

Thanks @Sreeja1725

2024-06-28 15:13 UTC, rthallisey commented
/approve

2024-06-28 15:33 UTC, alaypatel07 commented
/cherry-pick release-1.3

2024-06-28 16:00 UTC, lyarwood commented
PR looks great but a related question quickly while folks are looking at this for 1.3, I see the following still listed:

https://github.com/kubevirt/kubevirt/blob/2eb515574f9f963e9fe883f87f4bb5a31fa45cb9/docs/perf-scale-benchmarks.md#L22

Are there any plans to provide this? Is there anything I can do to help with this?

2024-06-28 18:34 UTC, alaypatel07 commented
@lyarwood yes there are a bunch of steps needed for getting the instance types metrics, your help will be very much appreciated. I think the best way would be to file an issue with sig/scale label so we can track it for 1.4 and discuss in sig-scale calls.

2024-06-28 22:38 UTC, alaypatel07 commented
/retest-required

2024-06-28 22:40 UTC, alaypatel07 commented
@xpivarc / @lyarwood someone needs to give this PR an approve tag. Please take a look, thanks

2024-07-02 07:24 UTC, xpivarc commented
@alaypatel07 @Sreeja1725 Do you want to re-run with https://github.com/kubevirt/kubevirt/pull/12249 ?

2024-07-02 12:22 UTC, alaypatel07 commented
@xpivarc the release benchmarks will not change since the fix will show data for 1.4 code due to branching. We don't have the ability to run on release branches yet.

2024-07-02 12:28 UTC, xpivarc commented
> @xpivarc the release benchmarks will not change since the fix will show data for 1.4 code due to branching. We don't have the ability to run on release branches yet.

Thanks
/approve

2024-07-02 20:28 UTC, merged