Move bash echo hello string to constant
kubevirt/kubevirt pull request #12257
Opened 2024-07-01 10:13 UTC by RoniKishner

### What this PR does
Before this PR:
The `"#!/bin/bash\necho 'hello'\n"` string would be used on several places through the repository

After this PR:
The string is moved into a constant and the constant is used instead

Fixes #11449 

### Special notes for your reviewer
The place that made most sense to me for the constant was storage.go, I would like to know if any reviewer thinks a better file is more suited for the constant. 

### Release note

```release-note
NONE
```

2024-07-01 10:52 UTC, orelmisan reviewed
Thank you for the PR @RoniKishner.

Is the approach taken in PR #12179 could be applicable here as well? 
Edit: Since the string is used in places which are not storage related (migration and VMI configuration tests), it makes sense to me to have the string constant in a central place, instead of under storage.

2024-07-01 11:27 UTC, RoniKishner commented
> Thank you for the PR @RoniKishner.
> 
> Is the approach taken in PR #12179 could be applicable here as well? Edit: Since the string is used in places which are not storage related (migration and VMI configuration tests), it makes sense to me to have the string constant in a central place, instead of under storage.

`$? Expands to the exit status of the most recently executed foreground pipeline.`
I don't think we should use it in this case, and about changing the file location can you give a suggestion as to which file to use? I couldn't find a central file besides utils.go, which I tried to prevent from using. 
Creating a new separate file for only constant and populating it with constants might be the best solution, but it is not in the scope of this PR, and can be discussed later.

2024-07-01 13:56 UTC, orelmisan commented
From a quick search, I found additional occurrences this string (or very similar) at:
- tests/libvmifact/factory.go (twice)
- tests/vm_test.go
- tests/migration/migration.go (two additional times)
- tests/storage/datavolume.go 
- tests/storage/migration.go

Please consider replacing them with the newly added const as well.

I tried to look for a more suitable place for the newly introduced constant, but couldn't find one (other than the infamous `tests/utils.go`).
Maybe people who are more familiar with the test code will have better advise.

2024-07-02 04:28 UTC, EdDev requested changes
The usages originated from the need to create VMI objects. Usually that means that the echo command was used to treat the boot process of the guest.

With the usage of libvmifact, this is an implementation detail.

I would recommend the following:
- In all places this string is used, convert it to use a libvmifact factory.
- If there are places where a factory is not possible, add a dedicated libvmi builder in libvmifact that abstracts this detail and expresses its purpose.
- For all other cases, explain why it is needed and not a fit to other options.

For clarification, IMO the constant should not exist. No one should be encouraged to use it in the codebase. Unless a very good reason is provided.

2024-07-09 08:33 UTC, RoniKishner commented
Closed in favor of #12304

2024-07-09 08:33 UTC, closed without merging