monitoring/vmistats_collector: update guest_os_machine label in vmi_info
kubevirt/kubevirt pull request #13010
Opened 2024-10-06 01:30 UTC by dasionov

### What this PR does
Before this PR:
the value from GuestOSInfo.Machine being evaluated by the guest-agent is the system-arch and not the actual machine-type-name from the domain-xml

After this PR:
this value is being label as guest_os_arch and the machine type is taken from the vmi.status.machine .type

Fixes #

### Why we need it and why it was done in this way
in order to track machine type in the vmi-info metric

### Release note
```release-note
None
```

2024-10-06 10:36 UTC, dasionov commented
/retest

2024-10-06 13:17 UTC, avlitman commented
Hi @dasionov great first sig/observability pr!! 

Please add the ticket number to the pr description using "jira-ticket: <full ticket url>"

Please update also (almost sure it's needed):
https://github.com/kubevirt/kubevirt/blob/f7a7c2f1797a032276e86cc96071c8d8a1c73d32/pkg/monitoring/rules/recordingrules/vmi.go#L32

other than that LGTM, just make sure manually you see the updated label, or add a test to check the label value is correct.

Thanks a lot (:

2024-10-06 13:47 UTC, avlitman commented
/lgtm 

cc @machadovilaca @sradco

2024-10-07 09:15 UTC, machadovilaca requested changes

2024-10-07 09:15 UTC, machadovilaca commented on pkg/monitoring/metrics/virt-controller/vmistats_collector.go
> +}
why didn't you update `getGuestOSInfo` to also include this label?

2024-10-07 09:15 UTC, machadovilaca commented on tests/monitoring/vm_monitoring.go
> +				"guest_os_arch":           agentVMI.Status.GuestOSInfo.Machine,
can't we test both "guest_os_machine" and "guest_os_arch"?

2024-10-07 09:15 UTC, machadovilaca commented on pkg/monitoring/metrics/virt-controller/vmistats_collector.go
> +		guestOSMachineArch = vmi.Status.GuestOSInfo.Machine
we are keeping the "guest_os_machine" and added "guest_os_arch" with the same values, is this intentional? some concern about compatibility?

2024-10-07 14:08 UTC, sradco commented
Hi @dasionov , Please add an example of the metric output to the PR description.

2024-10-07 14:50 UTC, dasionov commented
> Hi @dasionov , Please add an example of the metric output to the PR description.

Done :+1:

2024-10-07 20:06 UTC, fossedihelm commented
> Please add the ticket number to the pr description using "jira-ticket: full-ticket-url"

Actually the jira ticket is private :)

2024-10-08 09:44 UTC, dasionov commented
@sradco @machadovilaca
is there anything else needed for this PR to get approved ?

2024-10-09 11:49 UTC, sradco commented
/approve

2024-10-09 13:28 UTC, avlitman commented
/lgtm

2024-10-09 15:45 UTC, dasionov commented
/retest-required

2024-10-09 18:14 UTC, dasionov commented
/retest-required

2024-10-10 08:48 UTC, merged