Disable mpx only on x86
kubevirt/kubevirt pull request #13126
Opened 2024-10-25 15:02 UTC by xpivarc

### What this PR does

Fixes #

### Special notes for your reviewer

### Release note

```release-note
NONE
```

2024-10-25 15:03 UTC, xpivarc commented
/cc @vladikr

2024-10-25 15:18 UTC, vladikr commented
/approve
I'm fine with this change, however, @xpivarc  can you please fill out the description and add an issue if such exists?

2024-10-27 15:10 UTC, iholder101 commented
FYI @Barakmor1

2024-10-29 00:49 UTC, dasionov commented
Hi, could you add a quick note on why this change is needed? Just to make the purpose a bit clearer. Thanks!

2024-10-29 06:36 UTC, dankenigsberg requested changes

2024-10-29 06:36 UTC, dankenigsberg commented on pkg/virt-launcher/virtwrap/converter/converter.go
> +		if isAMD64(c.Architecture) && !exists && vmi.Spec.Domain.CPU.Model != v1.CPUModeHostModel && vmi.Spec.Domain.CPU.Model != v1.CPUModeHostPassthrough {
I believe that we must not have any `if architecture` in the main logic of our code. Any such logic should be delegated to an architecture-specific module. E.g. `archIface.IsCPUModelValid(CPU.Model)`

/cc @jschintag

2024-10-29 08:07 UTC, Barakmor1 commented
@xpivarc Is this a bug fix?
Wouldn't it be better to delete this code and address the issue in the releases where the bug exists? According to libvirt, the bug that required this quick workaround has been fixed:
https://gitlab.com/libvirt/libvirt/-/issues/608

I believe we are already including the libvirt version with the bug fix:
https://github.com/kubevirt/kubevirt/pull/12452

@andreabolognani WDYT?

2024-10-29 09:21 UTC, andreabolognani commented
@Barakmor1 I tried to understand the full context of the changes that have happened over time but I was not familiar with them before so I might have gotten some things wrong.

IIUC you added code that would explicitly disable the mpx feature in several cases because libvirt would otherwise complain about it not being supported on the host even when the named CPU model that was requested didn't actually need mpx.

Now that https://gitlab.com/libvirt/libvirt/-/issues/608 has been fixed (in libvirt 10.2.0, which is older than libvirt 10.5.0 currently used by KubeVirt) it should be possible to drop the hack, as libvirt will no longer perform additional checks for CPU models that QEMU has already reported as usable.

Assuming my understanding is correct and someone has verified that the issue which caused the hack to be added in the first place no longer affects KubeVirt, then I agree that the code should be dropped rather than updated.

2024-10-30 14:58 UTC, xpivarc commented
> /approve I'm fine with this change, however, @xpivarc can you please fill out the description and add an issue if such exists?

Done. Firstly I posted this for the user to try the fix.

2024-10-30 15:06 UTC, xpivarc commented
@Barakmor1 The description now contains the context. I did  not verify if we still need this hack nor I have time to do it at the moment. I need small, backportable fix which the PR is.

2024-10-30 15:06 UTC, xpivarc commented
/cherry-pick release-1.4
/cherry-pick release-1.3

2024-11-01 11:27 UTC, fossedihelm approved these changes
Looks reasonable as backportable fix

2024-11-01 17:35 UTC, merged