Add kubevirt_vmi_migration_size_bytes metric
kubevirt/kubevirt pull request #13423
Opened 2024-12-02 16:39 UTC by machadovilaca

### What this PR does
Before this PR:

No total constant amount for the total amount of data migrate

After this PR:

kubevirt_vmi_migration_size_bytes - The total Guest OS data to be migrated to the new VM.

Fixes jira-ticket: https://github.com/kubevirt/kubevirt/compare/main...machadovilaca:kubevirt:CNV-39060

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Add kubevirt_vmi_migration_size_bytes metric
```

2024-12-03 17:00 UTC, machadovilaca commented
/retest

2024-12-08 18:31 UTC, avlitman commented
nit: add the metric screenshot to the pr description

2024-12-09 09:58 UTC, machadovilaca commented
> nit: add the metric screenshot to the pr description

I have in the After this PR section

2024-12-09 10:54 UTC, machadovilaca commented
> nit: add the metric screenshot to the pr description

The screenshot is just a constant line, not very helpful I fear

2024-12-09 15:40 UTC, avlitman commented
just to make sure. did you test it catches all migrations? I saw in other metrics it didn't catch all of them.
If you can try to do few migration for 2 vmi will be great (:

2024-12-09 16:01 UTC, machadovilaca commented on pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
> +	 "DataTotalSet": false,
on the domain info we have 2 values for each, if the value is set, and the metric with the actual value
therefore
DataTotal - value
DataTotalSet - boolean saying if DataTotal is set or not

2024-12-09 16:11 UTC, sradco commented
> > nit: add the metric screenshot to the pr description
> 
> The screenshot is just a constant line, not very helpful I fear

I think Aviv meant if you can add to the description an example output of the metric, so that we and other reviewers can see the structure and labels it includes. Thanks.

2024-12-11 15:50 UTC, machadovilaca commented
> > > nit: add the metric screenshot to the pr description
> > 
> > 
> > The screenshot is just a constant line, not very helpful I fear
> 
> I think Aviv meant if you can add to the description an example output of the metric, so that we and other reviewers can see the structure and labels it includes. Thanks.

added

2024-12-12 09:54 UTC, avlitman commented
/lgtm

2024-12-12 13:50 UTC, sradco commented
Im missing information about the VM, namespace, node source and target and maybe additional. Please look at kubevirt_vmi_migration_data_processed_bytes as reference.

2024-12-12 14:33 UTC, machadovilaca commented
> Im missing information about the VM, namespace, node source and target and maybe additional. Please look at kubevirt_vmi_migration_data_processed_bytes as reference.

they are created the same way, how does `kubevirt_vmi_migration_data_processed_bytes` have more info?

2024-12-16 11:13 UTC, machadovilaca commented
> > Im missing information about the VM, namespace, node source and target and maybe additional. Please look at kubevirt_vmi_migration_data_processed_bytes as reference.
> 
> they are created the same way, how does `kubevirt_vmi_migration_data_processed_bytes` have more info?

cc @sradco

2024-12-26 14:13 UTC, avlitman commented
cc @enp0s3 This pr needs also an approve from core maintainer

2024-12-26 15:30 UTC, enp0s3 requested changes
@avlitman Thank you for the PR!
Can we add a functional test to see that it works end-to-end?

2025-01-06 11:44 UTC, machadovilaca commented
> @avlitman Thank you for the PR! Can we add a functional test to see that it works end-to-end?

@enp0s3 we are already validating the metric exists in functional test with non-zero value alongside other migrations metrics in https://github.com/kubevirt/kubevirt/pull/13423/files#diff-679184af10d0b8d9703feb21d657e8dcf3b834bacbcab6e3797439ec4f7f19c3R443

do you think we need more comprehensive testing for this metric?

2025-01-14 10:39 UTC, enp0s3 reviewed
@machadovilaca Hi, I see that metric type is gauge while the metric aim to count total bytes, does it make sense to use the counter type here?

2025-01-14 11:15 UTC, machadovilaca commented
> @machadovilaca Hi, I see that metric type is gauge while the metric aim to count total bytes, does it make sense to use the counter type here?

The metric is definitely a counter, but I'm not sure what the best approach here is, since these values come from the VM. I'm afraid the value can for some reason go down and Prometheus might treat it as a counter reset. What do you think?

2025-01-16 07:20 UTC, enp0s3 commented
@machadovilaca I think that in that case it will be even better to use counter. Then we will know that we can't rely only on scraping data from libvirt stats, but that we also need to persisnt and aggregate them with respect to the VM object lifecycle. During migration you collect data from source libvirt, but after the migration completes you have completely new pod with fresh libvirt, so it actually makes sense that the new libvirt will return zero value.

2025-01-16 14:24 UTC, enp0s3 commented
@machadovilaca Thank you!
/approve

2025-01-20 10:43 UTC, sradco commented on docs/observability/metrics.md
> +The total Guest OS data to be migrated to the new VM. Type: Counter.
@machadovilaca "to the new VM" or "to the new VMI" ?

2025-01-20 12:01 UTC, sradco commented
/lgtm

2025-01-21 02:58 UTC, merged