Allow podman for normal build steps
kubevirt/kubevirt pull request #4022
Opened 2020-08-19 19:39 UTC by rmohr

**What this PR does / why we need it**:

If docker is present and working, continue choosing docker. If it is not
present try to fallback to podman. In case that that KUBEVIRT_CRI
environment variable is set, try to use whatever is selected there.

Note that local test-cluster related operations like `make cluster-up` and `make cluster-sync` still require docker, but build steps like `make`, `make generate` or `make functest` work now with podman or docker.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-08-19 19:39 UTC, rmohr commented
/cc @EdDev 
/cc @danielBelenky 
/cc @dhiller

2020-08-19 19:43 UTC, enp0s3 requested changes

2020-08-19 19:43 UTC, enp0s3 commented on hack/dockerized
> +    if docke ps >/dev/null; then
@rmohr docke -> docker

2020-08-19 20:09 UTC, rmohr commented on hack/dockerized
> +    if docke ps >/dev/null; then
Fixed. Thx.

2020-08-20 04:53 UTC, EdDev reviewed
This is great, thanks!

Commit message typo: “that that”

2020-08-20 07:16 UTC, EdDev commented
/cc @phoracek

2020-08-20 07:43 UTC, phoracek commented
This fails for me when trying to build tests with following:

```
$ hack/dockerized hack/build-func-tests.sh
hack/dockerized: line 13: docker: command not found
selecting podman as container runtime
Trying to pull docker.io/kubevirt/builder@sha256:e6a76ec71f2de87c3bc648bae87ab43a113540bf57da69f07f76bd0edfd500ab...ERRO[0002] Error pulling image ref //kubevirt/builder@sha256:e6a76ec71f2de87c3bc648bae87ab43a113540bf57da69f07f76bd0edfd500ab: Digest of source image's manifest would not match destination reference 
Failed
Error: unable to pull kubevirt/builder@sha256:e6a76ec71f2de87c3bc648bae87ab43a113540bf57da69f07f76bd0edfd500ab: 1 error occurred:
        * Digest of source image's manifest would not match destination reference
```

2020-08-20 07:51 UTC, rmohr commented
/test pull-kubevirt-e2e-windows2016

2020-08-20 07:53 UTC, rmohr commented
@phoracek works for me:

```
$ podman pull docker.io/kubevirt/builder@sha256:e6a76ec71f2de87c3bc648bae87ab43a113540bf57da69f07f76bd0edfd500ab
Trying to pull docker.io/kubevirt/builder@sha256:e6a76ec71f2de87c3bc648bae87ab43a113540bf57da69f07f76bd0edfd500ab...
Getting image source signatures
Copying blob dfe6ecd6d77b skipped: already exists  
Copying blob 5cf469971bf6 skipped: already exists  
Copying blob 48699dca5da3 skipped: already exists  
Copying blob 95060617e71b skipped: already exists  
Copying blob b1833078a99d skipped: already exists  
Copying blob d1de41b0fa4e skipped: already exists  
Copying blob b0fe058ffda2 skipped: already exists  
Copying blob aafcb618b9d8 skipped: already exists  
Copying blob 70691977293d [--------------------------------------] 0.0b / 0.0b
Copying blob d0f8d8b071eb [--------------------------------------] 0.0b / 0.0b
Copying config c88a484b96 done  
Writing manifest to image destination
Storing signatures
c88a484b960b86d5b88a8258df50914417b1dbcc4e67ae61a666216e6bc12a75
```

podman version:

```
$ podman version
Version:      2.0.4
API Version:  1
Go Version:   go1.14.6
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

2020-08-20 08:14 UTC, phoracek commented
Must be my ancient Podman 1.4.2. I will upgrade my system and verify again.

2020-08-20 08:29 UTC, rmohr commented
/test pull-kubevirt-e2e-k8s-cnao-1.17
/test pull-kubevirt-generate

2020-08-20 08:32 UTC, rmohr commented
> Commit message typo: “that that”

Fixed.

2020-08-20 08:32 UTC, rmohr commented
/test pull-kubevirt-e2e-k8s-cnao-1.17
/test pull-kubevirt-generate

2020-08-20 08:33 UTC, dhiller commented on hack/dockerized
> +# Copy kubevirt into the persistent container volume
no trigger for dan here? :-)

2020-08-20 10:05 UTC, phoracek commented
After upgrading the system, it works fine with Podman 2.0.4.

2020-08-20 10:10 UTC, EdDev approved these changes
Thank you!

2020-08-25 11:16 UTC, merged