Prepare kubevirt for sonobuoy conformance testing
kubevirt/kubevirt pull request #4031
Opened 2020-08-20 16:26 UTC by rmohr

**What this PR does / why we need it**:

Build and release a conformance container which can be used for third parties to test ther kubevirt installation for conformance.
This initial implementation only marks one first single test  as a conformance test.

To generate a sonobuoy plugin for a released conformance test suite, run

```bash
$ sonobuoy gen plugin --name kubevirt-conformance --cmd /usr/bin/conformance --image kubevirt/conformance:<tag> -f junit > kubevirt.yaml
```
    
Then luanch the suite:
    
```bash
$ sonobuoy run --plugin kubevirt.yaml
```

Here a full flow in the development environment (note the `registry:500` prefix and the `:devel` tag:

```bash
$ sonobuoy gen plugin --name kubevirt-conformance --cmd /usr/bin/conformance --image registry:5000/kubevirt/conformance:devel -f junit > conformance.yaml
sonobuoy gen plugin --name kubevirt-conformance --cmd /usr/bin/conformance --image registry:5000/kubevirt/conformance:devel -f junit > conformance.yaml
$ sonobuoy retrieve
202008201609_sonobuoy_8f8d0b0e-1d37-485a-b61d-bf7185198fbf.tar.gz
$ sonobuoy results 202008201609_sonobuoy_8f8d0b0e-1d37-485a-b61d-bf7185198fbf.tar.gz
Plugin: kubevirt-conformance
Status: passed
Total: 580
Passed: 1
Failed: 0
Skipped: 579

```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Initial support for sonobuoy for conformance testing
```

2020-08-20 16:26 UTC, rmohr commented
/cc @phoracek 
/cc @EdDev 

Here a draft of what I would love to see regarding to conformance tests.

2020-08-25 11:07 UTC, rmohr commented
> Please add some documentation under docs/. The PR description looks pretty good, it could be more or less recycled.

Done. What I don't like is that there is no testing for it. We should probably at least have a periodic job which executs the conformance tests.The user-guilde should also be updated I guess.

2020-08-28 14:38 UTC, phoracek requested changes

2020-08-28 14:38 UTC, phoracek commented on tests/utils.go
> +func detectInstallNamesapce() {
namespace

2020-08-28 14:38 UTC, phoracek commented on docs/conformance.md
> +`v.33.0`. It can be executed as a [Sonobuoy](https://sonobuoy.io/) plugin to
v0.33.0

2020-08-28 14:47 UTC, rmohr commented on tests/utils.go
> +func detectInstallNamesapce() {
Done

2020-08-28 14:47 UTC, rmohr commented on docs/conformance.md
> +`v.33.0`. It can be executed as a [Sonobuoy](https://sonobuoy.io/) plugin to
Done.

2020-08-28 14:53 UTC, phoracek commented
/lgtm

2020-08-30 15:22 UTC, phoracek commented
/retest

2020-08-31 09:05 UTC, danielBelenky commented
/approve

2020-09-02 07:37 UTC, phoracek commented
/retest

2020-09-03 06:11 UTC, merged