Don't mutate container disk permissions
kubevirt/kubevirt pull request #4213
Opened 2020-09-18 19:55 UTC by davidvossel

If we mutate the permissions of the disk, then we cause the disk to be copied due to the container's layered filesystem. A container disk should never be altered. 

The disk either has the correct permissions necessary for qemu to access it, or it doesn't. If it doesn't, then the vmi will fail to boot. There's no action we can take to change or modify that on our end. 

```release-note
NONE
```

2020-09-19 05:53 UTC, rmohr requested changes
We know how the container disk in tests looks like. Can we extend the test to vheck that? Let's see that we get a failing test if the permission amor ownership changes.

I think this should be backported to every release with this bug. 

/kind bug

2020-09-21 06:31 UTC, danielBelenky requested changes

2020-09-21 06:31 UTC, danielBelenky commented on tests/container_disk_test.go
> -				readonlyImageOctalMode, err := tests.ExecuteCommandOnPod(
Maybe add a test that specifically ensures that we don't try to apply any modifications to the container-disk in such cases?

2020-09-22 07:55 UTC, rmohr commented
/cc @xpivarc @jean-edouard 

FYI, related to #3819.

2020-09-25 21:33 UTC, jean-edouard approved these changes

2020-09-28 12:02 UTC, jean-edouard commented
/retest

2020-09-28 16:00 UTC, davidvossel commented
/hold

After further investigation, I'm not sure this is really an issue

@rmohr After investigating this further, i'm not actually seeing the chmod cause any additional usage of storage space. I created a container disk with a 4gb disk and ran it in a replicaset of size 5. There was no increase in storage usage beyond the initial pull of the 4gb image.

maybe inode changes don't actually result in a modification to the file itself. The "modify" timestamp never changes on the disk image even after the chmod.

2020-09-29 12:48 UTC, rmohr commented
> maybe inode changes don't actually result in a modification to the file itself. The "modify" timestamp never changes on the disk image even after the chmod.

I am not sure we can make this asumption in general. Maybe some optimizations exist, but if I read for instance the `overlayfs` documentation (as said can be different in newer implementations): https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt, it says:

```
The copy_up process first makes sure that the containing directory
exists in the upper filesystem - creating it and any parents as
necessary.  It then creates the object with the same metadata (owner,
mode, mtime, symlink-target etc.) and then if the object is a file, the
data is copied from the lower to the upper filesystem.  Finally any
extended attributes are copied up.
```

which highlights that `mode` is part of what is tracked as content of the object.

2020-09-29 13:56 UTC, xpivarc commented
```
Metadata only copy up
--------------------

When metadata only copy up feature is enabled, overlayfs will only copy
up metadata (as opposed to whole file), when a metadata specific operation
like chown/chmod is performed. Full file will be copied up later when
file is opened for WRITE operation.
```

This is probably why the file is not being copied. But we should probably also consider other options than `overlayfs`.

2020-09-29 14:16 UTC, rmohr commented
> This is probably why the file is not being copied. But we should probably also consider other options than `overlayfs`.

Yes, thanks for digging that paragraph out. I think we should be on the save side here, since even in `overlayfs` it seems to be a features which is not necessarily enabled.

2020-10-13 21:11 UTC, davidvossel commented
@rmohr i changed things around a bit with regards to how our container disk images are built and tested.

I now set 444 at built time for our container disks. This should ensure we'll encounter issues in our functional tests if our runtime ever tries to mutate the disks. I also restored the vcheck in our functional test to verify that the mode is as we expect it based on what our build system is doing.

This verification doesn't guarantee us that we don't mutate the container disk image, but it at least verifies that the file permissions are what we'd expect.

2020-10-14 07:13 UTC, rmohr commented
/retest
/lgtm
/approve

2020-10-14 07:16 UTC, rmohr commented
/unhold

2020-10-15 04:49 UTC, merged