Revise DataVolumeTemplate API field
kubevirt/kubevirt pull request #4261
Opened 2020-09-24 21:09 UTC by davidvossel

The vm.Spec.DataVolumeTemplate api list actually contains DataVolumes rather than a struct that restricts the fields to only the metadata and spec. This gives the user the impression they can set things like the DataVolume group/kind and status when they in fact cannot. 

This change aligns our DataVolumeTemplate usage similar to how the PodTemplate works, by creating a new struct that only contains values a user can set.

I discovered this issue while reviewing this pr #3257 which adds the cdr validation schema back to our crd registrations. We're advertising DataVolume fields that users can't actually set. 

**Release note**:

```release-note
NONE
```

2020-09-24 21:10 UTC, davidvossel commented
/cc @xpivarc 

This will likely help us handle that strange datavolume exception logic you had to add to your explain pr.

2020-09-25 08:20 UTC, xpivarc requested changes
I agree with this but please see my  https://github.com/kubevirt/kubevirt/pull/3257#discussion_r494802331.

2020-09-25 08:20 UTC, xpivarc commented on staging/src/kubevirt.io/client-go/api/v1/types.go
> +	metav1.ObjectMeta `json:"metadata,omitempty"`
This needs to be added: `// +kubebuilder:pruning:PreserveUnknownFields`

2020-09-25 09:36 UTC, rmohr commented
/override pull-kubevirt-e2e-k8s-1.17

Error related to #4264, overriding.

/lgtm
/approve

2020-09-25 14:15 UTC, merged