virt-handler: restrict migration for specific CPU modes
kubevirt/kubevirt pull request #4323
Opened 2020-10-06 10:58 UTC by enp0s3

In the short-term we would like to disable migration capability for host-model and host-passthrough CPU
modes. A user can override that restriction by placing the following strings in the feature-gate:

```faeture-gate: "MigratableHostModel"``` will allow migration with host-model CPU
```faeture-gate: "MigratableHostPassthrough"``` will allow migration with host-passthrough CPU
```faeture-gate: "MigratableHostModel, MigratableHostPassthrough"``` will allow both.

**What this PR does / why we need it**:
By default, when a user configures a specific CPU model in the VM spec, it does not affect the scheduling of the virt-launcher pod itself since the CPU model isn't been considered as a criteria for node match (nodeSelector, node affinity, etc.).
However, in order to match node CPU capabilities with these defined in the VM spec it is required to set
```feature-gate: "CPUNodeDiscovery"``` In such case CPU specifics will be copied to the virt-launcher pod NodeSelector section.
The problem with host-model and host-passthrough modes is that CPU model is unknown at the scheduling stage, but 
only after the launch of the VM.

**Which issue(s) this PR fixes** 
https://bugzilla.redhat.com/show_bug.cgi?id=1760028

**Special notes for your reviewer**:

**Release note**:
```release-note
don't migrate VMs with host-model or host-passthrough CPU models
```

2020-10-06 10:58 UTC, enp0s3 commented
/hold
Holding this PR until we have a proper support in HCO API

2020-10-06 11:01 UTC, enp0s3 commented
/assign @fabiand @dankenigsberg

2020-10-06 11:51 UTC, dankenigsberg commented
> In the short-term we would like to disable migration capability for host-model and host-passthrough CPU
> modes. A user can override that restriction by placing the following strings in the feature-gate:

Please be explicit about the user persona. In this case, it is the cluster admin. A VM owner should not mess with feature gates.
Also, please mention that these gates should be opened if the admin knows that all nodes have equivalent CPU models, and would like to improve VM performance.

> 
> `faeture-gate: "MigratableHostModel"` will allow migration with host-model CPU

s/faeture/feature/

> `faeture-gate: "MigratableHostPassthrough"` will allow migration with host-passthrough CPU
> `faeture-gate: "MigratableHostModel, MigratableHostPassthrough"` will allow both.
> 
> **What this PR does / why we need it**:
> By default, when a user configures a specific CPU model in the VM spec, it does not affect the scheduling of the virt-launcher pod itself since the CPU model isn't been considered as a criteria for node match (nodeSelector, node affinity, etc.).
> However, in order to match node CPU capabilities with these defined in the VM spec it is required to set
> `feature-gate: "CPUNodeDiscovery"` In such case CPU specifics will be copied to the virt-launcher pod NodeSelector section.
> The problem with host-model and host-passthrough modes is that CPU model is unknown at the scheduling stage, but
> only after the launch of the VM.

Can you add a word (and a follow-up issue) about a longer-term solution, e.g. update CPU specs *after* the VMI is scheduled.

>  Holding this PR until we have a proper support in HCO API

thank - that's most important.

2020-12-04 14:35 UTC, vladikr commented
/retest

2020-12-07 16:06 UTC, vladikr requested changes
Overall, I'm fine with this approach right now. 
I do think that we can do a better job and allow kubvirt to translate the host-model to a known model and schedule according to this. However, this work will depend on https://github.com/kubevirt/kubevirt/pull/3498

@enp0s3 some comments inline.

2021-01-26 02:25 UTC, vladikr commented on tests/migration_test.go
> +				table.Entry("with cpu-passthrough", "host-passthrough", "MigratableHostPassthrough", false, false),
I guess s/MigratableHostModel/WithHostModelCPU and s/MigratableHostPassthrough/WithHostPassthroughCPU ?

2021-01-26 02:25 UTC, vladikr commented on tests/migration_test.go
> +				table.Entry("with cpu-passthrough", "host-passthrough", "MigratableHostPassthrough", true, true),
same as above?

2021-06-11 11:14 UTC, xpivarc commented
Should this be closed in favour of https://github.com/kubevirt/kubevirt/pull/5623 ?

2021-06-12 11:48 UTC, enp0s3 commented
/close
Will open a separate PR for CPU host passthrough handling.

2021-06-12 11:48 UTC, closed without merging