Automatically set disk I/O mode to the optimal value (native/threads)
kubevirt/kubevirt pull request #4421
Opened 2020-10-26 13:36 UTC by ezrasilvera

**What this PR does / why we need it**:
KubeVirt supports setting a disk I/O mode for disk devices.  There are currently two possible modes 
1.  io=native:  Using kernel async-io. 
1. io=threads: Using user-space threads to achieve (semi) async-I/O

Several investigations showed that on most cases the `native` option results in better I/O performance regardless of the workload and I/O pattern (i.e., requests/sec, size of requests, etc..). 
The only exception was in the case of file based disk with sparse file image. 

This means we can set an optimal disk I/O for the user within KubeVirt independently on the user future usage. 
We will set this mode automatically only in case the user didn't explicitly set that mode himself (we still allow the user to set it up directly)
The logic we take (to make sure we are on the safe side) is:  For block devices, and pre-allocated image disks - use `native`, for everything else don't set the mode explicitly. 

We don't set explicitly `thread` mode for sparse files because there might be use cases in which `native` will out-perform `threads` even for sparse files.

[1] https://web.archive.org/web/20180815010524/http://turlucode.com/qemu-disk-io-performance-comparison-native-or-threads-windows-10-version/
[2] http://docshare02.docshare.tips/files/17877/178771133.pdf
[3] https://www.slideshare.net/pradeepkumarsuvce/qemu-disk-io-which-performs-better-native-or-threads

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4077

**Special notes for your reviewer**:
Not to be confused with `iothreads` which can be orthogonal to this mode
**Release note**:

```release-note
"NONE"
```

2020-10-26 23:27 UTC, ezrasilvera commented
/retest

2020-10-27 08:34 UTC, rmohr commented
/cc @danielBelenky 

Daniel, could you have a look? I think you investigated exactly this in the past.

2020-10-27 08:41 UTC, ezrasilvera commented
/retest

2020-10-28 12:40 UTC, danielBelenky requested changes
@ezrasilvera could you please add tests?

2020-10-28 12:40 UTC, danielBelenky commented on pkg/virt-launcher/virtwrap/api/converter.go
> +	if diskInf.VirtualSize < diskInf.ActualSize {
Maybe for simplicity you could just do:
```
return diskInf.VirtualSize < diskInf.ActualSize
```

2020-10-28 12:40 UTC, danielBelenky commented on pkg/virt-launcher/virtwrap/api/converter.go
> +	// If the user explicitly set the io mmode do nothing
You have a typo here: s/mmode/mode

2020-10-28 13:06 UTC, ezrasilvera commented on pkg/virt-launcher/virtwrap/api/converter.go
> +	if diskInf.VirtualSize < diskInf.ActualSize {
Done

2020-10-28 13:06 UTC, ezrasilvera commented on pkg/virt-launcher/virtwrap/api/converter.go
> +	// If the user explicitly set the io mmode do nothing
Done

2020-10-28 19:53 UTC, ezrasilvera commented
/retest

2020-10-28 23:53 UTC, ezrasilvera commented
/retest

2020-10-29 08:13 UTC, ezrasilvera commented
/retest

2020-11-03 13:12 UTC, ezrasilvera commented
/retest

2020-11-06 00:24 UTC, ezrasilvera commented
/hold

2020-11-06 00:25 UTC, ezrasilvera commented
> @ezrasilvera could you please add tests?

In progress - working on this

2020-11-09 11:51 UTC, ezrasilvera commented
/unhold

2020-11-09 11:53 UTC, ezrasilvera commented
@danielBelenky I added functional test to test the new IO mode.

2020-11-09 12:17 UTC, ezrasilvera commented
/retest

2020-11-10 14:32 UTC, danielBelenky commented
/lgtm

2020-11-10 16:45 UTC, ezrasilvera commented
/retest

2020-11-12 13:03 UTC, rmohr commented
/approve

very nice.

2020-11-12 22:33 UTC, merged