test, cloudinit: Use "json" annotation instead of "yaml"
kubevirt/kubevirt pull request #4486
Opened 2020-11-03 11:45 UTC by qinqon

**What this PR does / why we need it**:
The networkData from cloud init is being rendered wrongly [1] since the actual yaml
parser that we use sigs.k8s.io/yaml don't understand the "yaml" annotation [2], using
"json" annotation fix the issue.

[1]  
```yaml
cloudInitNoCloud:
        networkData: |
          Ethernets:
            eth0:
              AcceptRA: null
              Addresses:
              - fd10:0:2::2/120
              DHCP4: true
              DHCP6: null
              DHCPIdentifier: ""
              Gateway4: ""
              Gateway6: fd10:0:2::1
              MACAddress: ""
              MTU: 0
              Nameservers:
                Addresses:
                - 10.96.0.10
                Search:
                - default.svc.cluster.local
                - svc.cluster.local
                - cluster.local
              Routes: null
          Version: 2
```

[2] https://play.golang.org/p/S0Pok-gGeQH

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-11-03 11:46 UTC, qinqon commented
/cc @EdDev

2020-11-03 11:49 UTC, EdDev approved these changes
Thank you and sorry you had to waste time on this.

2020-11-03 11:54 UTC, qinqon commented
I think we have to discover why tests are passing without it.

2020-11-03 15:28 UTC, qinqon commented
Added bazel BUILD files

2020-11-03 18:53 UTC, EdDev requested changes
This change can be split into two main changes:
- Fix the yaml annotations (1st commit).
- Use the cloud-init network config instead of the loggin IPv6 configuration.

If I understand correctly, the 2nd one is to confirm the 1st works.
It looks too big change to fit under the same intent here and I would have preferred to see it in a different PR. I hope we can combine it with [this one](https://github.com/kubevirt/kubevirt/pull/4362).

Regarding confirming that the 1st really works, I think we have a production issue.
If we take this simple [test](https://github.com/kubevirt/kubevirt/blob/88ddf9afc21dbbc8fe0260ecbf7d5514e35cdee6/tests/network/primary_pod_network.go#L105), it does no login at all, and still it checks that the pod and VMI reported IP/s match. But as we just found out when fixing the annotation, there is no IPv6 on the VM itself, so even though we have GA deployed, we are not reading from it the IP/s correctly, otherwise I would have expected the test to fail.

2020-11-03 18:53 UTC, EdDev commented on Makefile
> +
Changes in this file are probably leftovers.

2020-11-03 18:53 UTC, EdDev commented on tests/errors/panic.go
> +func PanicOnError(err error) {
If you created this one, why didn't you used it in the console/login.go ?
But I would prefer to see this in a different commit or better, in a different PR.

2020-11-03 18:53 UTC, EdDev commented on tests/libvmi/pod.go
> +func GetPodByVirtualMachineInstance(vmi *v1.VirtualMachineInstance, namespace string) *k8sv1.Pod {
How is this related to libnet ?

2020-11-03 18:53 UTC, EdDev commented on tests/login.go
>  	virtClient, err := kubecli.GetKubevirtClient()
Leftover?

2020-11-03 18:59 UTC, oshoval commented
didnt this PR was pure json / yaml change ? 
and the other was the one with all the ipv6 changes?

2020-11-04 12:14 UTC, fgimenez commented on tests/console/login.go
> +// LoginToCirros call LoggedInFedoraExpecter but does not return the expecter
`LoginToCirros` is still present in `tests/login.go`, these changes are duplicating it, shouldn't it be removed from there? Or maybe update the functions in `tests/console/login.go` to use the version in `tests/login.go`. Also, the version in this PR is not up to date, see https://github.com/kubevirt/kubevirt/blob/master/tests/login.go#L19-L26.

2020-11-10 09:21 UTC, closed without merging