virt-launcher, converter: Separate between the vCPU and queue count
kubevirt/kubevirt pull request #4657
Opened 2020-12-10 21:35 UTC by EdDev

**What this PR does / why we need it**:

The calculation of the vCPU and network queues should be independent of
each other. Specifically, the limit of a network queue (which originates
from the tap device limits) should not influence the vCPU count.

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2020-12-10 21:36 UTC, EdDev commented
/cc @maiqueb

2020-12-10 23:14 UTC, vladikr requested changes
/hold
I disagree with this statement.
I've explained the limitations in [1]
Making virtio-net queues scale with the number of vcpus the correct coupling, afaik.
From what I know so far, multi-queue support optimizes RX interrupt affinity and TX queue selection in order to make a specific queue private to a specific vCPU.

More information is available on the QEMU website[2], specifically: " multi-queue virtio-net, an approach enables packet sending/receiving processing to scale with the number of available vcpus of guest."

OpenStack takes the same approach that is proven to work [3]

[1]https://kubevirt.io/user-guide/#/creation/interfaces-and-networks?id=virtio-net-multiqueue
[2] http://www.linux-kvm.org/page/Multiqueue
[3] https://specs.openstack.org/openstack/nova-specs/specs/liberty/implemented/libvirt-virtiomq.html

2020-12-11 04:10 UTC, EdDev commented
Maybe my commit message is not phrased right. The queues are dependent on the vcpu and the tap device maximum values. But the vcpu is not limited by the tap device maximum queues (which is implied by the current code).
The bi-directional relation was very odd and this change suggests it should be kept uni-directional.

2020-12-11 13:32 UTC, EdDev commented
I tried to be more direct. Let me know if this is ok now.

2020-12-11 13:32 UTC, vladikr commented
My apologies. I didn't go further than the description.
That totally makes sense to split this `CalculateNetworkQueueNumberAndGetCPUTopology` function.

/hold cancel
/lgtm
/approve

2020-12-11 13:39 UTC, maiqueb approved these changes
Thanks!

2020-12-11 20:08 UTC, EdDev commented
/retest

2020-12-12 14:07 UTC, EdDev commented
/retest

2020-12-13 07:46 UTC, merged