cloud-init, GenerateLocalData:  simplify iso staging
kubevirt/kubevirt pull request #4724
Opened 2020-12-28 09:37 UTC by dankenigsberg

**What this PR does / why we need it**:    
GenerateLocalData creates a staging iso file, compares it to the production one, and replaces the production iso if their MD5 checksums are not equal.

The comparison take time in production, introduces code and complexity and opens the door to possible errors due to MD5 collisions. The cost of os.Rename is negligible. It is one of the quickest and safest file-related syscalls. This PR suggests to call os.Rename without comparison.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-12-28 14:53 UTC, dankenigsberg commented
the 1.17 (failure)[https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4724/pull-kubevirt-e2e-k8s-1.17/1343501802724659206] has in (virt-handler)[https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4724/pull-kubevirt-e2e-k8s-1.17/1343501802724659206/artifacts/k8s-reporter/1/pods/1_kubevirt_virt-handler-4shdp-virt-handler.log]
```
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvmi-cnqth","namespace":"kubevirt-test-default1","pos":"vm.go:1444","reason":"unknown error encountered sending command Kill: rpc error: code = DeadlineExceeded desc = context deadline exceeded","timestamp":"2020-12-28T11:17:31.866563Z","uid":"3febe021-eabb-4f6c-9fcf-6504aac3ac84"}
```

2020-12-29 08:53 UTC, rmohr commented
What I see is that the kubelet has issues removing the pod on a very low level:

```
Dec 28 11:17:14 node02 kubelet[2074]: E1228 11:17:14.771804    2074 remote_runtime.go:295] ContainerStatus "ca93e97f175b5eb9e13b99fe27496a75a0d774e75aa292f9a0baa589d9c1742f" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: ca93e97f175b5eb9e13b99fe27496a75a0d774e75aa292f9a0baa589d9c1742f
Dec 28 11:17:14 node02 kubelet[2074]: I1228 11:17:14.771841    2074 policy_static.go:249] [cpumanager] static policy: RemoveContainer (container id: c663783a4a06dbaf51013526c6813f804a1d27cfbf52e036a902d67b84de0188)
Dec 28 11:17:14 node02 kubelet[2074]: E1228 11:17:14.772228    2074 remote_runtime.go:295] ContainerStatus "c663783a4a06dbaf51013526c6813f804a1d27cfbf52e036a902d67b84de0188" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: c663783a4a06dbaf51013526c6813f804a1d27cfbf52e036a902d67b84de0188
Dec 28 11:17:14 node02 kubelet[2074]: I1228 11:17:14.772250    2074 policy_static.go:249] [cpumanager] static policy: RemoveContainer (container id: 0cca6909973cbf35fd429542a4bb367cf9a94b39c32b19a4affeae42ee17c059)
Dec 28 11:17:14 node02 kubelet[2074]: E1228 11:17:14.772722    2074 remote_runtime.go:295] ContainerStatus "0cca6909973cbf35fd429542a4bb367cf9a94b39c32b19a4affeae42ee17c059" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: 0cca6909973cbf35fd429542a4bb367cf9a94b39c32b19a4affeae42ee17c059
Dec 28 11:17:14 node02 kubelet[2074]: I1228 11:17:14.772750    2074 policy_static.go:249] [cpumanager] static policy: RemoveContainer (container id: 287f49e7c0466f5f60b7b03a34b52a526012198466f13756ecbc7809cbdead41)
Dec 28 11:17:14 node02 kubelet[2074]: E1228 11:17:14.773083    2074 remote_runtime.go:295] ContainerStatus "287f49e7c0466f5f60b7b03a34b52a526012198466f13756ecbc7809cbdead41" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: 287f49e7c0466f5f60b7b03a34b52a526012198466f13756ecbc7809cbdead41
```

We can check if we can handle such situations more correctly by still updating the status. It looks a little that virt-handler has issues with the half-shutdown pod. Maybe we can improve this a little. However the status would be reported correctly if virt-launcher would not have issues removing the pod.

It looks like the kubelet insists on a container being alive or present while the container runtime thinks that it does not exist (anymore):

```
Dec 28 11:17:14 node02 kubelet[2074]: E1228 11:17:14.773083    2074 remote_runtime.go:295] ContainerStatus "287f49e7c0466f5f60b7b03a34b52a526012198466f13756ecbc7809cbdead41" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: 287f49e7c0466f5f60b7b03a34b52a526012198466f13756ecbc7809cbdead41
```

2020-12-29 08:53 UTC, rmohr commented
/retest

2020-12-29 09:08 UTC, rmohr requested changes
The change looks good. Would you mind adding an explicit unit test which ensures that we can call `GenerateLocalData` multiple times, so that we are sure that it is still idempotent? The docs say so for `os.Rename` but better to have a test.

2020-12-29 11:01 UTC, rmohr approved these changes
/lgtm
/approve

2020-12-30 00:02 UTC, merged

2021-01-04 20:10 UTC, davidvossel commented
@dankenigsberg did you find this by profiling virt-launcher during the start process, or was this discovered while browsing the code? If there's profile data, that would be interesting to see. 

This change looks good, it's possible the whole reasoning behind why the md5 check and swap was introduced doesn't even exist anymore. It's probably safe to just generate the iso once, and only create it again if the file doesn't exist.

2021-01-06 12:42 UTC, dankenigsberg commented
@davidvossel I have no magic profilers, I'm afraid. I was moderately annoyed by carrying a known-broken crypto algorithm in KubeVirt; I wanted to replace it with proper file comparison, but then figured out that we do not need to `FilesAreEqual` at all.

2021-01-07 18:09 UTC, davidvossel commented
Ah, that makes sense. I was curious how you even found this logic. I haven't thought about that code in nearly 3 years.