make `make gosec` output slightly easier to find
kubevirt/kubevirt pull request #4802
Opened 2021-01-14 09:36 UTC by dankenigsberg

```release-note
NONE
```

2021-01-14 09:40 UTC, dankenigsberg commented
/cc @ezrasilvera

2021-01-23 15:12 UTC, ezrasilvera requested changes

2021-01-23 15:12 UTC, ezrasilvera commented on hack/gosec.sh
> +    echo "report written to" $(echo "$OUT" | sed 's/.*_out/_out/')
I agree it's better to move out the gosec command and just set the args differently in the GSEC condition,
If you want to print only in the fail case, I think  you may want to add and "else" with printout of "No errors detected" or something

2021-01-23 16:32 UTC, ezrasilvera commented
/lgtm

2021-02-23 16:13 UTC, dhiller commented
/test pull-kubevirt-gosec

2021-02-23 16:16 UTC, dhiller commented
/override pull-kubevirt-e2e-k8s-1.17

Unrelated and flaky test.

2021-02-23 17:05 UTC, dhiller commented
/approve

2021-02-23 17:16 UTC, merged