Support (non-)transitional virtio-balloon
kubevirt/kubevirt pull request #4862
Opened 2021-01-21 14:54 UTC by andreabolognani

**What this PR does / why we need it**:

Follow-up to https://github.com/kubevirt/kubevirt/pull/4730

There was a bug in libvirt that prevented virtio-balloon to be treated like other virtio devices, but that's been addressed now.

**Special notes for your reviewer**:

The mirror URLs (`https://storage.googleapis.com/builddeps/...`) for the new RPMs are not generated, because I have no idea how to make that happen and I probably don't even have the necessary permissions anyway O:-)

**Release note**:

```release-note
NONE
```

2021-01-21 14:55 UTC, andreabolognani commented
/cc @rmohr

2021-01-21 14:59 UTC, rmohr commented
> The mirror URLs (`https://storage.googleapis.com/builddeps/...`) for the new RPMs are not generated, because I have no idea how to make that happen and I probably don't even have the necessary permissions anyway O:

The mirror urls will be generated in a separate PR by our bot once this is merged, no action required.

2021-01-21 15:40 UTC, rmohr requested changes
Looks greast. One small request.

2021-01-21 15:40 UTC, rmohr commented on pkg/virt-launcher/virtwrap/converter/converter_test.go
> +			`<memballoon model="virtio-non-transitional">
Threr exists a unit test her which uses a function called `ExpectVirtioTransitionalOnly`, would you mind adjusting the checks in this function to also check the ballooning device?

2021-01-21 15:42 UTC, rmohr commented on pkg/virt-launcher/virtwrap/converter/converter_test.go
> +			`<memballoon model="virtio-non-transitional">
Never mind, you did that.

2021-01-21 15:42 UTC, rmohr approved these changes
My mistake, the test in question is already adjusted.

/lgtm
/approve

2021-01-21 18:56 UTC, rmohr commented
/lgtm cancel

The e2e result show 3 tests which need some more minor fixes.

2021-01-22 10:06 UTC, andreabolognani commented
@rmohr Fixed the functests, thanks for pointing the failure out!

2021-01-22 12:33 UTC, rmohr commented
/lgtm

2021-01-22 14:58 UTC, merged

2021-01-25 12:11 UTC, rmohr commented
/cherrypick release-0.36

2021-01-25 13:43 UTC, andreabolognani commented
@rmohr unfortunately a cherry-pick is not going to work, because 0.36 doesn't have bazeldnf :'(

One possible solution would be to make an ad-hoc rebuild of the kubevirt/libvirt container so that it includes the updated packages... While the kubevirt/libvirt repository is currently deprecated and Travis CI has become nigh useless in the past few months, everything is still set up, so we could create a branch there for this purpose.

What do you think?

2021-01-25 13:48 UTC, rmohr commented
> One possible solution would be to make an ad-hoc rebuild of the kubevirt/libvirt container so that it includes the updated packages... While the kubevirt/libvirt repository is currently deprecated and Travis CI has become nigh useless in the past few months, everything is still set up, so we could create a branch there for this purpose.
> 
> What do you think?

Please wait a little with that. I just wanted to have the PR prepared, but I don't think that we can merge it. Everything which is merged on that branch causes rebuilds in osbs. As far as I understand we don't have 8.3.1 yet available, so we would basically deliver a version which we can't yet use.

2021-01-25 13:55 UTC, andreabolognani commented
Alright, I'll let you handle it... Just let me know if I can be of assistance :)

2021-01-25 15:07 UTC, rmohr commented
> Alright, I'll let you handle it... Just let me know if I can be of assistance :)

Thanks. At some point we will need the rebuild for 0.36.