Migrate ipFamily fiels to k8s >= 1.20
kubevirt/kubevirt pull request #4896
Opened 2021-01-26 16:01 UTC by qinqon

**What this PR does / why we need it**:
Migrate ipFamily fiels to k8s >= 1.20

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2021-01-26 16:02 UTC, qinqon commented
/test all

2021-01-26 16:57 UTC, qinqon commented
/hold
Community has to decidy if bump and migrate or just migrate at least to unblock k8s-1.20 lane.

2021-02-01 09:20 UTC, maiqueb requested changes
I learnt something with this PR, was not aware of this unstructured option to create the resources.

I would encapsulate the proposed code into a couple of functions.

2021-02-01 09:20 UTC, maiqueb commented on pkg/virtctl/expose/expose.go
> +	}
Could you export this to a function ? 

`func getServerVersion(virtClient) (*ServerVersion, error) {...}` (I haven't checked the types exist... )

2021-02-01 09:20 UTC, maiqueb commented on pkg/virtctl/expose/expose.go
> +		//_, err = virtClient.CoreV1().Services(namespace).Create(service)
Leftover: remove the commented line.

2021-02-01 09:20 UTC, maiqueb commented on pkg/virtctl/expose/expose.go
> +		}
I'd also export this into a function, something like `morphServiceCreationRequest` or similar.

2021-02-01 09:20 UTC, maiqueb commented on pkg/virtctl/expose/expose.go
> +		}
I would furthermore create a new function `CreateService` function that would call the function above and would create these new types of services. I am struggling with naming this new `CreateService` function - create opposite of legacy service type is really bad ...

2021-02-01 11:30 UTC, closed without merging