Don't hardcode ci specific setups for docker
kubevirt/kubevirt pull request #5130
Opened 2021-03-01 23:00 UTC by rmohr

**What this PR does / why we need it**:

docker in CI is configured in a specific way with a specific CIDR. Two
tests are failing because they assume this address to be used by docker.

Removing this check for two reasons:

 1) It would require a specific ipv6 docker setup with a specific CIDR
 2) Without it no special docker configuration is necessary
 
The tests clearly fail locally if docker is not exactly configured like in CI.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2021-03-01 23:00 UTC, rmohr commented
/cc @fgimenez

2021-03-02 06:18 UTC, rmohr commented
/retest

2021-03-02 07:27 UTC, fgimenez approved these changes
/lgtm

2021-03-02 07:32 UTC, rmohr commented
/retest

2021-03-02 11:41 UTC, EdDev requested changes
This checks that the IPv6 configuration is able to exit the cluster to the "outside-world".
It follows similar tests in IPv4, however, there we check it against some internet IP/domains.

I agree that these tests cannot be assumed to pass, especially that they are marked as conformance tests. But the solution is also not to take them out completely, as they do check a reasonable functionality.

I would suggest to provide external ref addresses/domains (in the form of flags) to check against, so this can be managed by the one who runs the tests. If the values will not be provided, we can skip these checks.
On kubevirtci, we can keep on testing these, on other clusters it will be controlled by the one who runs it.

2021-03-02 11:46 UTC, EdDev commented
BTW, I am fine with reviving https://github.com/kubevirt/kubevirt/pull/5114 if you prefer to avoid running the these tests until we fix the hard coded values in the test.

2021-03-02 11:46 UTC, rmohr commented
> This checks that the IPv6 configuration is able to exit the cluster to the "outside-world".
> It follows similar tests in IPv4, however, there we check it against some internet IP/domains.
> 
> I agree that these tests cannot be assumed to pass, especially that they are marked as conformance tests. But the solution is also not to take them out completely, as they do check a reasonable functionality.
> 
> I would suggest to provide external ref addresses/domains (in the form of flags) to check against, so this can be managed by the one who runs the tests. If the values will not be provided, we can skip these checks.
> On kubevirtci, we can keep on testing these, on other clusters it will be controlled by the one who runs it.

/close

@EdDev feel free to do so.

2021-03-02 11:46 UTC, closed without merging