sriov, Remove unneeded eth0 ipv6 set in sriov tests
kubevirt/kubevirt pull request #5161
Opened 2021-03-07 10:53 UTC by oshoval

Sriov tests don't check the ipv6 of the pod network,
hence it's not needed.
The function that was removed also used hardcoded eth0,
which is not safe, because the primary network name
might not be eth0 (depends on the order the interfaces
were detected during boot sequence).

Signed-off-by: Or Shoval <oshoval@redhat.com>

```release-note
None
```

2021-03-07 10:53 UTC, oshoval commented
/cc @EdDev

2021-03-07 11:27 UTC, oshoval commented
Rebased

2021-03-07 11:48 UTC, EdDev requested changes
Thank you for this cleanup.

>  sriov, Remove unneeded eth0 ipv6 set in sriov tests

tests, sriov: Do not configure IPv6 on fedora-login

> 
> Sriov tests don't check the ipv6 of the pod network,
> hence it's not needed.

How is this related? I do not understand.

> The function that was removed also used hardcoded eth0,
> which is not safe, because the primary network name
> might not be eth0 (depends on the order the interfaces
> were detected during boot sequence).

This is partially correct. The interface name is controlled by cloud-init network settings which overwrites anything that relates to the boot sequence.
I think you can drop this in general, the reason to drop it is because we do not need to the the IPv6 configuration on login, we leave to the cloud-init network.
If you prefer to keep this, just make sure to be accurate to avoid confusion.

2021-03-07 12:33 UTC, oshoval commented
Addressed comments.

The configuration that was removed, is the default pod network one, that both not needed for sriov tests,
and also doesn't use the right method as you suggested, which is to use NetworkData, instead
using hardcoded eth0, which is prone to errors.
Updated description to reflect that.

2021-03-07 13:53 UTC, EdDev approved these changes
Thanks.

2021-03-07 14:02 UTC, oshoval commented
Thanks Edy

/cc @qinqon 
can you please take a look ?

2021-03-08 13:08 UTC, AlonaKaplan commented
/approve

2021-03-08 13:18 UTC, oshoval commented
Thanks Alona

2021-03-09 09:08 UTC, merged