Refactor func hostdisk.Create
kubevirt/kubevirt pull request #5307
Opened 2021-03-24 10:20 UTC by tompsota

Refactor the function so its cognitive complexity
is reduced below 15 and corresponding sonarcloud
issue is fixed.

Signed-off-by: Tomas Psota <tpsota@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2021-03-25 08:54 UTC, rhrazdil commented
/ok-to-test

2021-03-26 09:20 UTC, tompsota commented
/retest

2021-03-29 08:16 UTC, rhrazdil requested changes
Thanks! Looking good.
Two comments

2021-03-29 08:16 UTC, rhrazdil commented on pkg/host-disk/host-disk.go
> +			if err := mountHostDiskAndSetOwnership(vmi, hdc, volume.Name, hostDisk); err != nil {
Since we're now passing the `hdc DiskImgCreator` as an argument repeatedly, we may want to pass a reference to it, so it's not copied every time

2021-03-30 07:03 UTC, rhrazdil approved these changes
Thanks! Looks good to me
/lgtm

2021-03-30 08:10 UTC, tompsota commented
/retest

2021-03-30 10:03 UTC, tompsota commented
/retest

2021-04-20 12:13 UTC, enp0s3 requested changes
@tompsota Hi. Thank you for the PR. Overalls looks good. I think you can turn the newly created functions into a receiver functions `func (hdc *DiskImgCreator)...` and you can use a pointer receiver to avoid redundant copies. That will also spare you from passing `&hdc` to each and every function you've created for this flow.

2021-04-21 21:51 UTC, enp0s3 approved these changes
Thank you!
/approve

2021-04-23 00:17 UTC, merged