s/Runnig/Running/ in tests
kubevirt/kubevirt pull request #5377
Opened 2021-04-01 12:52 UTC by maya-r

Fix a common typo

**Release note**:

```release-note
NONE
```

2021-04-01 13:03 UTC, ashleyschuett approved these changes

2021-04-01 13:22 UTC, EdDev reviewed
I am unsure that we need these helpers now.
The only `kind` cluster is SR-IOV and non of these tests are expected to run there.

This may have been a leftover from when removing the IPv6 kind lane.

2021-04-01 13:26 UTC, EdDev commented
> EDIT: Can you perhaps just try to remove these?

Please unhold if it does not work.
/hold

2021-04-04 16:37 UTC, EdDev approved these changes
Thank you!

/unhold

2021-04-20 13:41 UTC, maya-r commented
/hold
Sending a cautious email to kubevirt-dev and waiting 2 weeks before merging.

2021-04-21 10:48 UTC, enp0s3 requested changes
@maya-r Hi. Thank you for the PR. Just to be on the safe side- if someone would try to run the e2e suite on an external cluster (we allow this by setting `KUBEVIRT_PROVIDER=external`) can you please make sure we have a warning in the documentation about using KIND provider in combination with these tests?

2021-04-21 12:15 UTC, maya-r commented
Apparently that file comes from kubevirtci.

2021-04-21 15:10 UTC, enp0s3 approved these changes
/approve

2021-05-03 11:57 UTC, maya-r commented
Fixed merge conflict.
Will abuse this almost-no-changes pull request to test an optional lane before enabling it. Sorry for the noise.

/test pull-kubevirt-e2e-k8s-1.20-rook-ceph

2021-05-03 12:38 UTC, maya-r commented
/test pull-kubevirt-e2e-k8s-1.20-rook-ceph

2021-05-03 15:55 UTC, maya-r commented
No replies, assuming it's fine.
/hold cancel

2021-05-03 16:05 UTC, EdDev approved these changes

2021-05-06 07:31 UTC, merged