virt-chroot envinfo flag, reporting user and capabilities
kubevirt/kubevirt pull request #5388
Opened 2021-04-04 16:50 UTC by EdDev

**What this PR does / why we need it**:
Introduce a global flag to the `virt-chroot` binary that reports verbose environment information.

The information includes at this stage user info and process capabilities.

Use the `--envinfo` flag to enable this additional info.

It is included in the tap device creation operation. Intended to help debug the random failure seen at the tap creation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

2021-04-04 16:50 UTC, EdDev commented
/cc @AlonaKaplan

2021-04-05 11:22 UTC, qinqon requested changes
Looks good, small issue at error catching.

2021-04-05 11:22 UTC, qinqon commented on cmd/virt-chroot/envinfo.go
> +	caps.Load()
Missing error catching https://github.com/syndtr/gocapability/blob/master/capability/capability.go#L56

2021-04-05 13:45 UTC, EdDev commented on cmd/virt-chroot/envinfo.go
> +	caps.Load()
Done

2021-04-06 05:23 UTC, qinqon requested changes
Looks good, added one little catch and some suggestions.

2021-04-06 05:23 UTC, qinqon commented on cmd/virt-chroot/envinfo.go
> +func reportCapabilities(pid int32) error {
Use pie argument here

2021-04-06 05:23 UTC, qinqon commented on cmd/virt-chroot/envinfo.go
> +	fmt.Printf("Capabilities:\n%s\n\n", caps)
What about using log package sometimes is good to have the time stamp

2021-04-06 05:23 UTC, qinqon commented on cmd/virt-chroot/main.go
> +	addEnvInfoPersistentFlag(rootCmd)
Don't create a function for this, do it like the others.

2021-04-07 04:05 UTC, EdDev commented
The info learned from this change is confirming what we already knew: the process inherits the user and caps of its parent (virt-handler) and there are no surprises here.

Therefore there is no point to take this in.

/hold

2021-04-19 05:57 UTC, closed without merging