Virt chroot create tap debug
kubevirt/kubevirt pull request #5390
Opened 2021-04-04 21:20 UTC by EdDev

**What this PR does / why we need it**:
Add debug information to the virt-chroot binary when creating a tap device and use it from network phase 1.

The following actions/information are added with this change:
- Allow to retry the tap device creation.
- Allow to create a dummy-bridge as a ref to the tap creation attempt (to check if both or only one fails).
- Report the network links seen by the process on failure to create the tap device.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This PR depends on #5388 

**Release note**:
```release-note
NONE
```

2021-04-04 21:21 UTC, EdDev commented
/cc @AlonaKaplan 
/cc @maiqueb

2021-04-04 21:21 UTC, EdDev commented
/uncc mhenriks

2021-04-05 04:19 UTC, EdDev commented
Use for debugging at the moment.
We should reconsider this only if we fail to recreate the issue.

/hold

2021-04-05 05:51 UTC, EdDev commented
/test pull-kubevirt-e2e-k8s-1.18
/test pull-kubevirt-e2e-k8s-1.19
/test pull-kubevirt-e2e-k8s-cnao-1.19
/test pull-kubevirt-e2e-k8s-network-1.19

2021-04-05 10:15 UTC, EdDev commented
/test pull-kubevirt-e2e-k8s-1.18
/test pull-kubevirt-e2e-k8s-1.19
/test pull-kubevirt-e2e-k8s-cnao-1.19

2021-04-05 13:53 UTC, qinqon requested changes
We can use rtry package

2021-04-05 14:17 UTC, EdDev commented on cmd/virt-chroot/tap-device-maker.go
> +}
Yes we probably can, but I really do not want to add dependencies on something that simple.
We also use the the cobra-command and fetch the flag that is currently specific to the tap-create command.

This is also not targeted to get merged, just to provide debug info.

2021-04-05 16:22 UTC, EdDev commented
/test pull-kubevirt-e2e-k8s-1.18
/test pull-kubevirt-e2e-k8s-1.19
/test pull-kubevirt-e2e-k8s-cnao-1.19

2021-04-05 16:22 UTC, EdDev commented
/retest

2021-04-05 21:50 UTC, EdDev commented
/test pull-kubevirt-e2e-k8s-1.18
/test pull-kubevirt-e2e-k8s-1.19
/test pull-kubevirt-e2e-k8s-cnao-1.19

2021-04-06 03:54 UTC, EdDev commented
Incident occurred:  https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5390/pull-kubevirt-e2e-k8s-1.18/1379189784194322432

2021-04-19 05:59 UTC, closed without merging