chore(ADOPTERS.md): addition of Civo
kubevirt/kubevirt pull request #5516
Opened 2021-04-22 14:41 UTC by AlexsJones

Signed-off-by: Alex <alexsimonjones@gmail.com>

Addition of [Civo](https://www.civo.com) into Adopters list.
Thanks

```release-note
NONE
```

2021-04-25 11:26 UTC, dankenigsberg requested changes
/ok-to-test

2021-04-25 11:26 UTC, dankenigsberg commented on ADOPTERS.md
> +| [Civo](https://www.civo.com) | 2020 | We are using Kubevirt as part of our stack to enable tenant cluster provisioning within Civo cloud. |
```suggestion
| [Civo](https://www.civo.com) | 2020 | We are using KubeVirt as part of our stack to enable tenant cluster provisioning within Civo cloud. |
```

2021-04-25 17:25 UTC, AlexsJones commented
> @AlexsJones: The following tests **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-kubevirt-e2e-k8s-1.17-rook-ceph	[dd3d9a7](https://github.com/kubevirt/kubevirt/commit/dd3d9a7c46a207e65a491496120841030f6e092c)	[link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5516/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1386280502528315392)	`/test pull-kubevirt-e2e-k8s-1.17-rook-ceph`
> pull-kubevirt-e2e-k8s-1.18	[dd3d9a7](https://github.com/kubevirt/kubevirt/commit/dd3d9a7c46a207e65a491496120841030f6e092c)	[link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5516/pull-kubevirt-e2e-k8s-1.18/1386280502436040704)	`/test pull-kubevirt-e2e-k8s-1.18`
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

/retest

2021-04-27 20:42 UTC, davidvossel reviewed
/approve

2021-04-27 21:12 UTC, dankenigsberg commented on ADOPTERS.md
> +| [Civo](https://www.civo.com) | 2020 | We are using Kubevirt as part of our stack to enable tenant cluster provisioning within Civo cloud. |
@AlexsJones would you accept this suggestion?

2021-04-30 18:28 UTC, fabiand commented
/lgtm

2021-05-03 04:35 UTC, merged