remove apis being depricated in k8s 1.22
kubevirt/kubevirt pull request #6048
Opened 2021-07-15 16:38 UTC by ashleyschuett

Signed-off-by: Ashley Schuett <aschuett@redhat.com>

**What this PR does / why we need it**:

These APIs are being removed in k8s 1.22. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Update v1beta1 apis to v1
```

2021-07-15 16:38 UTC, ashleyschuett commented
/hold 

blocked by https://github.com/kubevirt/kubevirtci/pull/640

2021-07-15 17:58 UTC, davidvossel approved these changes
/approve

2021-07-15 17:59 UTC, davidvossel commented
/lgtm cancel

2021-07-16 11:08 UTC, rmohr commented
/lgtm
/unhold
/retest

Tests seem to be fine now.

2021-07-16 11:17 UTC, rmohr requested changes
/lgtm cancel

2021-07-16 11:17 UTC, rmohr commented on cluster-up/cluster/kind/manifests/kube-calico.yaml.in
> -apiVersion: apiextensions.k8s.io/v1beta1
Oh this file is coming from `kubevirt/kubevirtci` and has to be changed there.

2021-08-11 11:22 UTC, rmohr commented
/retest

2021-08-11 13:05 UTC, ashleyschuett commented
closing due to merge of https://github.com/kubevirt/kubevirtci/pull/644

2021-08-11 13:05 UTC, closed without merging