[WIP] Inclusive text
kubevirt/kubevirt pull request #6050
Opened 2021-07-15 22:09 UTC by stu-gott

In an effort to conform to current coding practices, I've cleaned up some references to terms such as whitelist/blacklist or master/slave where possible.

Please note, we've already switched to using the "main" branch in this repo, so this PR also corrects issues with our documentation.

**Release note**:
```release-note
Changed some terminology to be more inclusive
```

2021-07-15 22:11 UTC, stu-gott commented
I'm currently considering this PR to currently be a draft. there's a surprising amount of complexity to these changes--there's a fair amount of external dependency that needs to be inspected.

2021-07-16 11:07 UTC, rmohr requested changes
Looks very good already. A quick check showed three places where `master` is still required.

2021-07-16 11:07 UTC, rmohr commented on hack/gen-client-python/deploy.sh
> +    git push origin main >/dev/null 2>&1
I think this has to stay with `master` until the target repo is switched.

2021-07-16 11:07 UTC, rmohr commented on hack/gen-swagger-doc/deploy.sh
> +    git push origin main >/dev/null 2>&1
The same here. Has to stay on `master` for now.

2021-07-16 11:07 UTC, rmohr commented on hack/publish-staging.sh
> +    if [ "${TARGET_BRANCH}" == "main" ]; then
Same here.

2021-07-30 19:49 UTC, stu-gott commented
Thanks @rmohr, I realized I was too aggressive on my first pass, but clearly missed a few instances.

I think there's at least one follow-on PR if we'd like to address node labels and the like, but that's slightly invasive so I think this PR should be considered for inclusion as-is.

2021-07-30 20:43 UTC, jean-edouard commented on CONTRIBUTING.md
> +Please have a look at our [membership guidelines](https://github.com/kubevirt/community/blob/main/membership_policy.md).
The name change hasn't happened yet there...

2021-07-30 20:43 UTC, jean-edouard commented on CONTRIBUTING.md
> +  * [Kubernetes Architecture](https://github.com/kubernetes/community/blob/main/contributors/design-proposals/architecture/architecture.md)
Same as above. How about moving the changes to this file to a later PR, to avoid blocking the rest of this one?

2021-07-30 20:43 UTC, jean-edouard commented on docs/devel/networking.md
> +be attached to the in-pod bridge as its port, and the tap device's MAC address,
`as its port` sounds weird, maybe just remove?

The original page makes it sounds like bridges have... primary and secondary ports. This is typically not the case for basic linux bridges, in which case we're good. However, if the original page is correct, then this version loses that distinction.

2021-07-30 20:43 UTC, jean-edouard commented on docs/devel/storage.md
> +cluster-up/kubectl.sh apply -f https://raw.githubusercontent.com/kubevirt/containerized-data-importer/main/manifests/controller/cdi-controller-deployment.yaml
This repo has already renamed its main branch, however that file is nowhere to be found...
Maybe it moved to another repo?

2021-07-30 20:43 UTC, jean-edouard commented on docs/update-go-version.md
> +* Use [project-infra's uploader tool](https://github.com/kubevirt/project-infra/blob/main/plugins/cmd/uploader/README.md) to upload new dependencies to dependency mirror.
404. Moved there? https://github.com/kubevirt/project-infra/blob/main/robots/cmd/uploader/README.md

2021-07-30 20:43 UTC, jean-edouard commented on hack/publish-staging.sh
> +if [ -z "${TARGET_TAG}" ] && [ "${TARGET_BRANCH}" != "master" ]; then
I'm confused, why are we replacing a "main" to a "master" here?

2021-07-30 20:43 UTC, jean-edouard commented on manifests/testing/rook-ceph/operator.yaml
> +        # http://docs.ceph.com/docs/latest/cephfs/experimental-features/#multiple-filesystems-within-a-ceph-cluster
Looks like it's actually https://docs.ceph.com/en/latest/cephfs/experimental-features/#multiple-filesystems-within-a-ceph-cluster

2021-11-19 15:07 UTC, fossedihelm commented
I think this can be closed since these commits has been cherry picked in the [#6814](https://github.com/kubevirt/kubevirt/pull/6814)

2021-11-19 15:17 UTC, closed without merging