Perform teardown before each test starts on SRIOV tests suite
kubevirt/kubevirt pull request #6267
Opened 2021-08-19 06:51 UTC by ormergi

Signed-off-by: Or Mergi <ormergi@redhat.com>

**What this PR does / why we need it**:
The SRIOV test suite designed to avoid using the the general func
for test teardown [1] before each test starts.
Instead [1] is called once before all tests starts,
due to that VMI's clean up is done in-place before each test starts.

The VMI's clean up doesn't handle VMI's that take longer time
or stuck in the Terminating phase.
Due to the fact that VMI's clean up occurs before tests starts,
when it fails the test that about to start reported as it was failed
instead of the one that just finished.

This PR Changes SRIOV test suite to use 'BeforeTestCleanup'
before each test starts, will clean up VMI's properly
and prevent reporting wrong test failures.

In order to make use of [1], NAD's creating is moved to tests
spec instead before all tests start.

[1] https://github.com/kubevirt/kubevirt/blob/8f8a93245fc6bbaf881470f0ec97dcdae5ede8b8/tests/utils.go#L491

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Recently we started to saw  that one of the tests fails from time to time due to VM's that wont dispose, and due to how the test suite works the wrong test is reported as failure.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6231/pull-kubevirt-e2e-kind-1.19-sriov/1425816945118154752
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6182/pull-kubevirt-e2e-kind-1.19-sriov/1425895209576697856

**Release note**:

```release-note
NONE
```

2021-08-22 15:57 UTC, ormergi commented
/cc @EdDev

2021-08-22 19:01 UTC, EdDev requested changes
Looks like a good opertunity to remove the `BeforeAll`.
See details inline.

2021-08-22 19:01 UTC, EdDev commented on tests/network/vmi_multus.go
> +			Expect(createNetworkAttachementDefinition(sriovnet1, util.NamespaceTestDefault, sriovConfCRD)).To((Succeed()), "should successfully create the network")
I prefer for this change, just to place it all in the `BeforeEach` and not distribute it all over.
We need to re-organize the tests here, lets defer this part to that step.

2021-08-24 11:47 UTC, EdDev approved these changes
Lets start with something and then we will worry about the rest.

Thanks!

2021-08-29 11:35 UTC, ormergi commented
/retest

2021-08-29 11:38 UTC, ormergi commented
> @ormergi unit tests [failing](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-unit-test/1431065531342917632)?!
> 
> ```

I think its transient or has been fixed, this PR doesn't even touch the code that could affect those tests

2021-08-29 11:40 UTC, ormergi commented
> @ormergi unit tests [failing](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-unit-test/1431065531342917632)?!
> 
> ```
>  E0827 01:35:05.946225      12 runtime.go:76] Observed a panic: sync: negative WaitGroup counter 
> ```
> 
@dankenigsberg I think its transient or has been fixed, this PR doesn't even touch code that could affect those tests

2021-08-29 12:14 UTC, dankenigsberg commented
@ormergi clearly this PR is not causing these failed unit test; but we ensure that unit test cannot be flaky. I see this two often.

2021-08-30 07:51 UTC, ormergi commented
@davidvossel @enp0s3 I think we have a problem with k8s-1.20-sig-storage lane, since this PR wont affect storage tests can we override it?

2021-08-30 08:13 UTC, dankenigsberg commented
> @davidvossel @enp0s3 I think we have a problem with k8s-1.20-sig-storage lane, since this PR wont affect storage tests can we override it?

The storage sig, say @maya-r @awels @aglitke, should be aware of this.

2021-08-30 08:16 UTC, maya-r commented
I've proposed https://github.com/kubevirt/project-infra/pull/1121 to avoid blocking kubevirt asap (while looking for more fixes)

2021-08-30 08:33 UTC, ormergi commented
> I've proposed [kubevirt/project-infra#1121](https://github.com/kubevirt/project-infra/pull/1121) to avoid blocking kubevirt asap (while looking for more fixes)

I am not sure how its going to mitigate k8s-1.20-sig-storage lane, here we can see it keeps blocking

2021-08-30 08:46 UTC, maya-r commented
oops. https://github.com/kubevirt/project-infra/pull/1520

2021-08-30 08:57 UTC, ormergi commented
> oops. [kubevirt/project-infra#1520](https://github.com/kubevirt/project-infra/pull/1520)

Thanks!

@fedepaol I see that merging kubevirt/project-infra#1520 caused retest for all lanes, is it correct?
1.20 and 1.19 sig-storage  lanes are still marked as required, would it be merged anyway?

2021-08-30 09:04 UTC, fgimenez commented
> @fedepaol I see that merging [kubevirt/project-infra#1520](https://github.com/kubevirt/project-infra/pull/1520) caused retest for all lanes, is it correct?

I see that lanes that already passed are not being rebuilt right? like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-e2e-k8s-1.19-sig-storage/1431804818728423424, is that correct? and poor Federico Paolinelli :)  

> 1.20 and 1.19 sig-storage lanes are still marked as required, would it be merged anyway?

where do you see that? In the summary of the checks I see that 1.20-sig-storage and 1.19-sig-storage don't have the "Required" label anymore, see screenshot attached.

![Screenshot from 2021-08-30 11-02-45](https://user-images.githubusercontent.com/70376/131315006-21c9b547-948a-4b86-b07d-1d8c5675b18d.png)

2021-08-30 09:05 UTC, fedepaol commented
> > @fedepaol I see that merging [kubevirt/project-infra#1520](https://github.com/kubevirt/project-infra/pull/1520) caused retest for all lanes, is it correct?
> 
> I see that lanes that already passed are not being rebuilt right? like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-e2e-k8s-1.19-sig-storage/1431804818728423424, is that correct? and poor Federico Paolinelli :)
> 


Lol I don't mind remembering my old project from time to time :P


> > 1.20 and 1.19 sig-storage lanes are still marked as required, would it be merged anyway?
> 
> where do you see that? In the summary of the checks I see that 1.20-sig-storage and 1.19-sig-storage don't have the "Required" label anymore, see screenshot attached.
> 
> ![Screenshot from 2021-08-30 11-02-45](https://user-images.githubusercontent.com/70376/131315006-21c9b547-948a-4b86-b07d-1d8c5675b18d.png)

2021-08-30 09:08 UTC, ormergi commented
> I see that lanes that already passed are not being rebuilt right? like https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-e2e-k8s-1.19-sig-storage/1431804818728423424, is that correct? and poor Federico Paolinelli :)
> 

Ohh I am so sorry my bad :sweat:

I am not sure because I see that the rest of sig lanes are triggered

> where do you see that? In the summary of the checks I see that 1.20-sig-storage and 1.19-sig-storage don't have the "Required" label anymore, see screenshot attached.
> 

I guess its updated now, when writing that comment it was marked as required

2021-08-30 09:37 UTC, fgimenez commented
> I am not sure because I see that the rest of sig lanes are triggered

Yes, maybe related to how tide works with merge batches and not related to the change in the storage lanes, in any case it seems that already green lanes are not re-built.

2021-08-30 10:37 UTC, fgimenez commented
`pull-kubevirt-e2e-k8s-1.21-sig-network` failed with a test that was removed from quarantine recently https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-e2e-k8s-1.21-sig-network/1432264444922040320

2021-08-30 10:58 UTC, EdDev commented
> `pull-kubevirt-e2e-k8s-1.21-sig-network` failed with a test that was removed from quarantine recently https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-e2e-k8s-1.21-sig-network/1432264444922040320

This seems a different issue than the one originally quarantined and fixed.
The IP address for the secondary interface is not reflected on the VMI state [1], although already set in the guest.

We need to monitor this one, to see if it occurs frequent. The 2 minutes seems to be enough, so it is strange to see this occurring.

[1]
```
                "interfaces": [
                    {
                        "ipAddress": "10.244.196.159",
                        "mac": "52:54:00:d0:2a:14",
                        "name": "default",
                        "ipAddresses": [
                            "10.244.196.159",
                            "fd10:244::c49d"
                        ],
                        "interfaceName": "eth0"
                    },
                    {
                        "mac": "02:03:04:05:06:aa",
                        "name": "net1",
                        "interfaceName": "eth1"
                    }
                ]
```

2021-08-30 11:49 UTC, ormergi commented
> > `pull-kubevirt-e2e-k8s-1.21-sig-network` failed with a test that was removed from quarantine recently https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6267/pull-kubevirt-e2e-k8s-1.21-sig-network/1432264444922040320
> 
> This seems a different issue than the one originally quarantined and fixed.
> The IP address for the secondary interface is not reflected on the VMI state [1], although already set in the guest.
> 
> We need to monitor this one, to see if it occurs frequent. The 2 minutes seems to be enough, so it is strange to see this occurring.
> 
> [1]
> 
> ```
>                 "interfaces": [
>                     {
>                         "ipAddress": "10.244.196.159",
>                         "mac": "52:54:00:d0:2a:14",
>                         "name": "default",
>                         "ipAddresses": [
>                             "10.244.196.159",
>                             "fd10:244::c49d"
>                         ],
>                         "interfaceName": "eth0"
>                     },
>                     {
>                         "mac": "02:03:04:05:06:aa",
>                         "name": "net1",
>                         "interfaceName": "eth1"
>                     }
>                 ]
> ```

I think it happens because we assert on the VMI status w/o making sure QEMU guest agent is up.
I posted a PR to add it https://github.com/kubevirt/kubevirt/pull/6318

2021-08-30 12:00 UTC, ormergi commented
/retest

2021-08-30 13:13 UTC, fgimenez commented
> I think it happens because we assert on the VMI status w/o making sure QEMU guest agent is up.
> I posted a PR to add it #6318
> 
> EDIT: I am not sure its the root cause, but its still necessary.

thanks a lot, another failure here https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6312/pull-kubevirt-e2e-k8s-1.21-sig-network/1432303029054345216

2021-08-30 22:26 UTC, merged