Properly process Gateway DHCP Option as IPv4 in DHCP Server
kubevirt/kubevirt pull request #6465
Opened 2021-09-27 23:32 UTC by salanki

PR requested by @maiqueb 

**What this PR does / why we need it**:
This PR fixes https://github.com/kubevirt/kubevirt/issues/6462, the behavior and need for the PR is extensively detailed there. The `.IPv4()` on the gateway IP can safely be done in `server.go` as it is the last place it is touched before handed over to the DHCP library.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubevirt/kubevirt/issues/6462

**Special notes for your reviewer**:

**Release note**:
```release-note
Fix corrupted DHCP Gateway Option from local DHCP server, leading to rejected IP configuration on Windows VMs.
```

2021-09-27 23:34 UTC, salanki commented
/cc @phoracek

2021-09-28 08:41 UTC, maiqueb requested changes
I'm missing a unit test for this change. 

Please just add the following snippet to https://github.com/kubevirt/kubevirt/blob/236eb73ed2af4d698ab943fd4340bda9747757eb/pkg/network/dhcp/server/server_test.go#L246

```golang
It("expects the gateway as an IPv4 addresses", func() {
    gw := net.ParseIP("192.168.2.1")
    options, err := prepareDHCPOptions(gw.DefaultMask(), gw, nil, nil, nil, 1500, "myhost", nil)
    Expect(err).NotTo(HaveOccurred())
    Expect(options[dhcp4.OptionRouter]).To(Equal([]byte{192, 168, 2, 1}))
})
```

I've checked that without your fix the test fails with:
```bash
• Failure [0.000 seconds]
DHCP Server
.../kubevirt/pkg/network/dhcp/server/server_test.go:33
  Options returned by prepareDHCPOptions
  .../kubevirt/pkg/network/dhcp/server/server_test.go:203
    expects the gateway as an IPv4 addresses [It]
    .../kubevirt/pkg/network/dhcp/server/server_test.go:248

    Expected
        <[]uint8 | len:16, cap:16>: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 192, 168, 2, 1]
    to equal
        <[]uint8 | len:4, cap:4>: [192, 168, 2, 1]
```

2021-09-28 15:12 UTC, salanki commented
Test failure seems unrelated. I am submitting updated patch with a unit test soon, then we can retest.

2021-09-28 15:19 UTC, maiqueb commented
> Test failure seems unrelated. I am submitting updated patch with a unit test soon, then we can retest.

/ok-to-test

@salanki now you should be able to `/retest` / `/test <test lane name>` on this PR .

2021-09-28 15:25 UTC, salanki commented
Unit test is now in place, tests succeed locally

2021-09-28 15:26 UTC, maiqueb approved these changes
Thanks for the PR.

2021-09-28 17:55 UTC, vladikr commented
/retest

2021-09-28 18:44 UTC, vladikr commented
/approve

2021-09-28 19:14 UTC, merged

2021-09-29 15:15 UTC, maiqueb commented
IIUC, the community thinks this is a good candidate to be back-port to 0.43 - 0.45 . 

@vladikr should I instruct the bot to start the process ?

2021-10-07 07:13 UTC, rmohr commented
/cherrypick release-0.43

2021-10-07 07:13 UTC, rmohr commented
/cherrypick release-0.44

2021-10-07 07:14 UTC, rmohr commented
/cherrypick release-0.45