Merge SSH, SSHOptions structs.
kubevirt/kubevirt pull request #6919
Opened 2021-12-07 12:28 UTC by maya-r

Avoid passing arguments lots of times.
No functional change intended.

**Release note**:

```release-note
NONE
```

2021-12-07 12:28 UTC, maya-r commented
fyi @rmohr

2021-12-09 09:32 UTC, rmohr requested changes
Thanks for tackling this. I think we can make it a little bit more future-proof by keepint the SSHOptions struct and just adding it to the new `SSH` struct. I tried to outline it in a comment. Let me know if it does not make sense for you.

2021-12-12 12:07 UTC, maya-r commented on pkg/virtctl/ssh/ssh.go
> +	c := &SSH{
Done

2021-12-13 12:08 UTC, rmohr commented
/retest

2021-12-14 07:48 UTC, merged