Trigger audit from inside the performance test
kubevirt/kubevirt pull request #7057
Opened 2022-01-12 02:22 UTC by rthallisey

I noticed after the func test runs, the namespace used by the density test gets cleaned up.  That could be why we're seeing inconsistent results for the density test.  So instead of calling the audit tool after the func test runs, call it from inside the func test.   Calling from inside the func tests makes sense for future tests too since we'll want to call perf audit `afterEach` test.
```
------------------------------
• [SLOW TEST:89.300 seconds]
[sig-performance][Serial] Control Plane Performance Density Testing
tests/performance/framework.go:57
  Density test
  tests/performance/density.go:68
    [small] create a batch of 20 VMIs
    tests/performance/density.go:72
      should sucessfully create all VMIS
      tests/performance/density.go:73
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
S [SKIPPING] in Spec Setup (BeforeEach) [0.000 seconds]
[sig-performance][Serial] CPU latency tests for measuring realtime VMs performance
tests/performance/framework.go:57
  running cyclictest and collecting results directly from VM [BeforeEach]
  tests/performance/realtime.go:83

  Realtime performance tests are not enabled

  tests/performance/framework.go:72
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Waiting for namespace kubevirt-test-default1 to be removed, this can take a while ...
Waiting for namespace kubevirt-test-alternative1 to be removed, this can take a while ...
Waiting for namespace kubevirt-test-operator1 to be removed, this can take a while ...
```

We'll see if this yields more consistent results in the periodic job.  Here are the result from a local run:
```
{
  "Values": {
    "CREATE-events-count": {
      "value": 78.61666666666667
    },
    "CREATE-pods-count": {
      "value": 19.283333333333335
    },
    "GET-endpoints-count": {
      "value": 145.36095688012753
    },
    "GET-nodes-count": {
      "value": 126.08333333333334
    },
    "LIST-clusterrolebindings-count": {
      "value": 1.4833333333333334
    },
    "LIST-customresourcedefinitions-count": {
      "value": 2.966666666666667
    },
    "LIST-daemonsets-count": {
      "value": 2.966666666666667
    },
    "LIST-deployments-count": {
      "value": 1.4833333333333334
    },
    "LIST-jobs-count": {
      "value": 1.4833333333333334
    },
    "LIST-kubevirts-count": {
      "value": 1.4833333333333334
    },
    "LIST-limitranges-count": {
      "value": 1.4833333333333334
    },
    "LIST-poddisruptionbudgets-count": {
      "value": 1.4833333333333334
    },
    "LIST-rolebindings-count": {
      "value": 1.4833333333333334
    },
    "LIST-roles-count": {
      "value": 1.4833333333333334
    },                                                                                                                                                                                                                                         
    "LIST-virtualmachineclusterflavors-count": {
      "value": 2.966666666666667
    },
    "LIST-virtualmachineflavors-count": {
      "value": 1.4833333333333334
    },
    "LIST-virtualmachineinstances-count": {
      "value": 1.4833333333333334
    },
    "PATCH-pods-count": {
      "value": 32.63333333333333
    },
    "PATCH-virtualmachineinstances-count": {
      "value": 29.666666666666668
    },
    "UPDATE-endpoints-count": {
      "value": 89
    },
    "UPDATE-virtualmachineinstances-count": {
      "value": 204.7
    },
    "running-phase-count": {
      "value": 20
    },
    "vmiCreationToRunningSecondsP50": {
      "value": 31
    },
    "vmiCreationToRunningSecondsP95": {
      "value": 40.000000000000036
    },
    "vmiCreationToRunningSecondsP99": {
      "value": 47.99999999999999
    }
  }
}
```

Signed-off-by: Ryan Hallisey <rhallisey@nvidia.com>

```release-note
NONE
```

2022-01-12 02:22 UTC, rthallisey commented
@davidvossel @marceloamaral

2022-01-12 02:26 UTC, rthallisey commented
/retest

2022-01-12 08:04 UTC, marceloamaral requested changes
Thanks @rthallisey!

So I'm not sure if this will solve the problem, running the audit tool in or out the test should give the same result.
Getting the results after namespace deletion shouldn't be a problem. In fact, it should be even more accurate as we can get the DELETE events.
But, I'm fine with this change if you want to go ahead with it.

By the way, there are some parts that might be interesting to update.

Not all requests succeed, some fail (e.g. 4.. and 5.. http response code)
```
sum(increase(rest_client_requests_total{pod=~"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*"}[360s])) by (code, container, verb, job, method) > 0

{code="200", container="virt-api", method="GET", verb="LIST"} | 19.63764314193006
{code="404", container="virt-operator", method="GET", verb="GET"} | 1.0909090909090908
```

So, I suggest counting only the requests with code 2... Also, it might be better to aggregate the metrics in prometheus.
`sum(increase(rest_client_requests_total{pod=~"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*", code=~"2.."}[%ds]) ) by (verb, method, resource) > 0`

I'm also including the label `method` because in OpenShift CNV v0.44.3, the `rest_client_requests_total` has no `verb` but only `method` label. So if possible, could you also change it in the code, try using `method` when there is no `verb` label?

2022-01-12 08:12 UTC, marceloamaral commented
Also, the idea is to replace the density test as a functional test with the `perfscale-load-generator` tool.
As done here: kubevirt/project-infra/pull/1819

2022-01-12 12:03 UTC, rthallisey commented
> So I'm not sure if this will solve the problem, running the audit tool in or out the test should give the same result. Getting the results after namespace deletion shouldn't be a problem. In fact, it should be even more accurate as we can get the DELETE events.
>
I don't know if this will work, but I want to narrow down the possibility that this is due to when we run the audit tool.  Also, I rarely see the DELETE events in the periodic job, which lends to the theory that this is timing based.

2022-01-12 12:09 UTC, rthallisey commented
>So, I suggest counting only the requests with code 2... Also, it might be better to aggregate the metrics in prometheus.
sum(increase(rest_client_requests_total{pod=~"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*", code=~"2.."}[%ds]) ) by (verb, method, resource) > 0
>
My goal for this PR is to eliminate the possibility we have a timing issue.  If this PR doesn't fix anything, I think it has to do with what we're doing with prometheus or both!

2022-01-12 21:50 UTC, rthallisey commented
/retest

2022-01-12 21:50 UTC, rthallisey commented
rebased

2022-01-12 21:55 UTC, davidvossel approved these changes
/lgtm
/approve

I'm doubtful that this will fix the inaccuracy issues we're seeing, but it doesn't hurt

2022-01-12 23:30 UTC, rthallisey commented
/retest

2022-01-13 15:05 UTC, marceloamaral commented
I found some interesting results about this problem

First, related to the CREATE and DELETE event.
I did a test sleeping 60s before and 120s after the execution with the following timestamps:
start Thu Jan 13 13:06:38 UTC 2022
end Thu Jan 13 13:10:45 UTC 2022

![image](https://user-images.githubusercontent.com/5133121/149336996-cc6c720c-afff-486c-b50f-d9fcf18c83a0.png)

 
However, as you can see the experimented finished at 13:10:45 and there was a sleep of 120s before collecting the results, but the DELETE event only appeared 10 seconds later at 13:10:55. Not sure why, but to collect it we need to wait more time. Maybe 3mim might be a safe marge.

On the other hand, the CREATE event appeared 12:10:24. So, there is no need to wait 60s before running the test.

However, this is only one part of the history.
The previous experiment where executed when kubevirt was already previously installed.
When I run the test just after the kubevirt installation many metrics does not appear in prometheus...
Even after a sleep of 180s before running the test!
![image](https://user-images.githubusercontent.com/5133121/149349735-447c4264-ac14-4a2e-a368-a2ba816d7de4.png)

2022-01-13 20:34 UTC, merged