Refactor the Load Generator and Support SteadyState Types
kubevirt/kubevirt pull request #7265
Opened 2022-02-22 15:11 UTC by rthallisey

Refactor the load generator code.

- Define workload types as an interface so it can be extended to accommodate each job type
- Add support for steady-state job
- Simplify the config (rely on outside scripts to handle ns creation, iterations, ect...)

Test below shows a steady-state workload with `churn: 2` `count: 5`.  This will create 5 VMIs and delete 2 VMIs frequently over a `5m` period.
```
name: kubevirt-steady-state-test
timeout: 5m
count: 5
churn: 2
type: "steady-state"
object:
  templateFile: vmi-ephemeral.yaml
  inputVars:
    containerPrefix: quay.io/kubevirt
    containerImg: cirros-container-disk-demo
    containerTag: ""
    namespace: default
```
<img width="1696" alt="Screen Shot 2022-02-22 at 9 31 36 AM" src="https://user-images.githubusercontent.com/6795213/155159856-c350ff63-c59c-446d-b358-d8bc585c785e.png">

**Release note**:
```release-note
Support steady-state job types in the load-generator tool
```

Future work:
- The SteadyState `CreateWorkload` is really the same as Burst `CreateWorkload`.  Call Burst create from SteadyState.
- Refacore the Watcher package

2022-02-22 15:11 UTC, rthallisey commented
/cc @marceloamaral @davidvossel

2022-02-24 14:59 UTC, rthallisey commented
cc @marceloamaral @davidvossel

2022-03-03 08:29 UTC, marceloamaral requested changes
This PR will affect two prow jobs. So before merging this, you also need another PR to fix those jobs.

[periodic-kubevirt-performance-cluster-100-density-test](https://github.com/kubevirt/project-infra/blob/163333c8ef4085a6a8805a05d610879b34c69d15/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml#L792)

[periodic-kubevirt-performance-cluster-scale-density-test](https://github.com/kubevirt/project-infra/blob/163333c8ef4085a6a8805a05d610879b34c69d15/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml#L792)

Both jobs execute the [automation/perfscale-test.sh](https://github.com/kubevirt/kubevirt/blob/main/automation/perfscale-test.sh), which run the perfscale-load-generator tool. You also need to update this script accordingly to the new logic.

/hold

2022-03-03 08:29 UTC, marceloamaral commented on tools/perfscale-load-generator/object/unstructured.go
> +	//	virtv1 "kubevirt.io/api/core/v1"
Probably a left over to be removed

2022-03-07 18:49 UTC, rthallisey commented on tools/perfscale-load-generator/config/config.go
> +	config.Burst = Burst
I wanted to reduce config options.  I default to `20` which should be plenty for the time being.

2022-03-07 19:39 UTC, rthallisey commented
/retest

2022-03-07 20:14 UTC, rthallisey commented
created https://github.com/kubevirt/project-infra/pull/1946.  I think this change can go in first and 1946 can quickly follow.

2022-03-07 20:14 UTC, rthallisey commented
/unhold

2022-03-10 14:54 UTC, rthallisey commented
/retest

2022-03-10 16:18 UTC, rthallisey commented on tools/perfscale-load-generator/config/config.go
> +	config.Burst = Burst
Changed both to unlimited.  We can come back and change this as the tool matures.

2022-04-07 12:41 UTC, marceloamaral commented
/retest
/lgtm

2022-04-14 14:09 UTC, rthallisey commented
/retest

2022-04-20 17:28 UTC, rthallisey commented
rebased.  @marceloamaral need another lgtm from you

2022-04-21 12:48 UTC, rthallisey commented
/retest

2022-04-22 01:43 UTC, marceloamaral commented
/lgtm

2022-04-22 08:45 UTC, merged