tests: make secondary NIC configurable
kubevirt/kubevirt pull request #7327
Opened 2022-03-08 14:12 UTC by jean-edouard

**What this PR does / why we need it**:
Dedicated migration network tests currently fail on clusters nodes that use another NIC than eth1, since the value is hardcoded.
This PR makes it configurable at runtime.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2022-03-08 14:13 UTC, jean-edouard commented
/cherry-pick release-0.49

2022-03-08 19:53 UTC, enp0s3 approved these changes
/approve

2022-03-08 20:35 UTC, jean-edouard commented
Added an environment variable to make it simpler to configure.
@xpivarc PTAL!

2022-03-09 06:43 UTC, EdDev requested changes
There are potentially multiple secondary networks, each with their own nic.
This addition seems to serve only the migration network, and it may be more appropriate to input to the tests the *migration network nic*, which is more focused to the issue in hand. In the current form, there is still one thing hardcoded: the nic that is to be used.

It would also be nice to add to the commit message the reasoning for this configurable setting.

> Dedicated migration network tests currently fail on clusters nodes that use another NIC than eth1, since the value is hardcoded.

Could you please ref to such a setup? Are we talking about non kubevirtci setup?

2022-03-09 13:25 UTC, jean-edouard commented
> There are potentially multiple secondary networks, each with their own nic. This addition seems to serve only the migration network, and it may be more appropriate to input to the tests the _migration network nic_, which is more focused to the issue in hand. In the current form, there is still one thing hardcoded: the nic that is to be used.

Renamed to "migration network nic".

> 
> It would also be nice to add to the commit message the reasoning for this configurable setting.
> 
> > Dedicated migration network tests currently fail on clusters nodes that use another NIC than eth1, since the value is hardcoded.

Done.

> 
> Could you please ref to such a setup? Are we talking about non kubevirtci setup?

Yes, any non-kubevirtci setup where the desired nic is not eth1.

2022-03-09 13:28 UTC, EdDev approved these changes
Thank you!

2022-03-10 02:41 UTC, merged