Remove the logic and TODO
kubevirt/kubevirt pull request #7344
Opened 2022-03-10 12:08 UTC by ZP-AlwaysWin

Signed-off-by: ZP-AlwaysWin <zhangpeng63@baidu.com>

**What this PR does / why we need it**:

VMI is initialized for the first time. There is no labels
And the objectmeta has been assigned as a whole，There is no need to assign values to labels
```
...
vmi.ObjectMeta = vm.Spec.Template.ObjectMeta
...
# This is unnecessary
vmi.ObjectMeta.Labels = vm.Spec.Template.ObjectMeta.Labels
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2022-03-10 12:09 UTC, ZP-AlwaysWin commented
/assign @jean-edouard

2022-03-11 02:32 UTC, ZP-AlwaysWin commented
/ok-to-test

2022-03-11 02:48 UTC, ZP-AlwaysWin commented
/assign @rmohr

2022-03-16 09:44 UTC, ZP-AlwaysWin commented
/assign @omeryahud

2022-03-28 07:48 UTC, ZP-AlwaysWin commented
> Looks good. Could you unit test this change?

Thanks Already added unit test for this change

2022-03-28 09:06 UTC, ZP-AlwaysWin commented
> Could you squash the commit, please?

done

2022-03-30 10:09 UTC, ZP-AlwaysWin commented
Please review it. Thank you @xpivarc @rmohr

2022-03-30 11:23 UTC, xpivarc approved these changes

2022-05-16 10:48 UTC, xpivarc requested changes
Sorry for the late reply

2022-05-16 10:48 UTC, xpivarc commented on pkg/virt-controller/watch/vm_test.go
> +			labels := vm1.GetLabels()
You want to add the labels to `vm1.Spec.Template.ObjectMeta.Labels`, right?

2022-10-25 04:55 UTC, closed without merging