Clean Code: replace equal("") with BeEmpty()
kubevirt/kubevirt pull request #7373
Opened 2022-03-16 10:54 UTC by nunnatsa

**What this PR does / why we need it**:
Use the dedicated ginkgo matcher `BeEmpty()` for empty strings, instead of using `equal("")`, in order to get better error description and more readable test code.

**Release note**:

```release-note
None
```

2022-03-16 11:10 UTC, maiqueb approved these changes
Thank you.

2022-03-16 11:11 UTC, maiqueb commented
only thing I wonder is if we really need 26 commits to change this. All in one, its one change.

2022-03-16 11:52 UTC, nunnatsa commented
/retest

2022-03-16 12:37 UTC, nunnatsa commented
/retest

2022-03-16 12:49 UTC, nunnatsa commented
/retest

2022-03-16 13:28 UTC, nunnatsa commented
/retest

2022-03-17 11:44 UTC, nunnatsa commented
/retest

2022-03-17 12:53 UTC, acardace commented
> only thing I wonder is if we really need 26 commits to change this. All in one, its one change.

I agree, it seems a bit overkill, you can probably just squash everything into 1 commit and add the command you used to do the replacing (if any) in the commit msg.

2022-03-17 13:56 UTC, nunnatsa commented
> > only thing I wonder is if we really need 26 commits to change this. All in one, its one change.
> 
> I agree, it seems a bit overkill, you can probably just squash everything into 1 commit and add the command you used to do the replacing (if any) in the commit msg.

@acardace @maiqueb - fixed.

2022-03-17 17:17 UTC, nunnatsa commented
/tetest

2022-03-17 18:53 UTC, nunnatsa commented
/tetest

2022-03-17 19:13 UTC, nunnatsa commented
/test pull-kubevirt-e2e-k8s-1.21-sig-compute
/test pull-kubevirt-e2e-k8s-1.23-sig-network
/test pull-kubevirt-e2e-k8s-1.23-sig-storage-cgroupsv2

2022-03-17 19:37 UTC, nunnatsa commented
/test pull-kubevirt-e2e-windows2016

2022-03-20 12:41 UTC, enp0s3 approved these changes
/approve

2022-03-20 18:28 UTC, nunnatsa commented
/retest

2022-03-21 07:38 UTC, nunnatsa commented
/test pull-kubevirt-e2e-kind-1.22-sriov

2022-03-21 08:11 UTC, EdDev requested changes
> Use the dedicated ginkgo matcher BeEmpty() for empty strings, instead of using equal(""), in order to get better error description and more readable test code.

If the equality is on strings, I do not understand what better description will the `BeEmpty` give here. When you mention "more readable test code", what do you mean exactly? Why is it better reading that an explicit empty string?
I think you need to elaborate a bit to convince this is indeed better.

I can give here a counterpart reasoning why this may not be better: Using `Equal` is strict about types (at least per the documentation) while `BeEmpty` is not.

I usually use `BeEmpty` for checking arrays, slices and maps, as these may come as "empty" or `nil`, both valid in terms of usage in code (and interchangeable most of the time).
Still, we do loose the type checking, but in those cases I think it is worth it.
I am not that sure if it is valid for strings as well.

I would also recommend splitting this into two commits: One for the production code and one for the e2e tests.

2022-03-21 08:11 UTC, EdDev commented on pkg/virt-operator/resource/apply/core_test.go
> +		It(`should not patch if ClusterIp == "" during update`, func() {
This change (and there are other I think), do not fit the same commit (or even PR) as the subject.
Can you extract it to a different PR?

2022-04-13 09:03 UTC, closed without merging