[Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in template test
kubevirt/kubevirt pull request #7381
Opened 2022-03-16 11:44 UTC by iholder-redhat

**What this PR does / why we need it**:
This small PR replaces all appearences of `Expect(len(X)).To(Equal(Y))` to `Expect(X).To(HaveLen(Y))` for better readability and error presentation.

**Release note**:

```release-note
NONE
```

2022-03-18 15:06 UTC, dankenigsberg approved these changes

2022-03-18 15:09 UTC, jean-edouard requested changes
Found a couple of `HaveLen(0)`, sounds like we want `BeEmpty()` instead.

2022-03-18 18:36 UTC, dankenigsberg requested changes

2022-03-18 18:36 UTC, dankenigsberg commented on pkg/virt-controller/services/template_test.go
> +				Expect(pod.Spec.InitContainers).To(HaveLen(0))
/lgtm cancel

Right!

2022-03-20 10:11 UTC, iholder-redhat commented on pkg/virt-controller/services/template_test.go
> +				Expect(pod.Spec.InitContainers).To(HaveLen(0))
Fixed.

2022-03-20 10:11 UTC, iholder-redhat commented
> Found a couple of `HaveLen(0)`, sounds like we want `BeEmpty()` instead.

Fixed.

2022-03-20 10:27 UTC, dankenigsberg approved these changes

2022-03-20 14:05 UTC, iholder-redhat commented
/retest

2022-03-20 14:17 UTC, enp0s3 commented
/approve

2022-03-20 21:11 UTC, merged