conditions: refactor unit test
kubevirt/kubevirt pull request #7400
Opened 2022-03-17 10:11 UTC by acardace

Replace occurrences of `Expect(len($VAR)).To(Equal($X))` with
`Expect($VAR).To(Equal($X)` which is more gomega-idiomatic and gives
better error messages when the expectation fails.

Signed-off-by: Antonio Cardace <acardace@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2022-03-17 10:23 UTC, maiqueb requested changes
I think your commit msg and PR description is incorrect; it states:
```
Replace occurrences of `Expect(len($VAR)).To(Equal($X))` with
`Expect($VAR).To(Equal($X)` which is more gomega-idiomatic and gives
better error messages when the expectation fails.
```
And your commit adds `Expect(X).To(HaveLen(Y))` . You should reference the `HaveLen` gomega matcher, rather than `Equal`.

2022-03-17 12:46 UTC, acardace commented
> I think your commit msg and PR description is incorrect; it states:
> 
> ```
> Replace occurrences of `Expect(len($VAR)).To(Equal($X))` with
> `Expect($VAR).To(Equal($X)` which is more gomega-idiomatic and gives
> better error messages when the expectation fails.
> ```
> 
> And your commit adds `Expect(X).To(HaveLen(Y))` . You should reference the `HaveLen` gomega matcher, rather than `Equal`.

Oops, you're right! Thanks for catching that!

2022-03-17 12:50 UTC, maiqueb approved these changes
Thank you !

2022-03-18 15:07 UTC, jean-edouard commented
/approve
/hold
Can the commit title be adjusted? I wouldn't say this PR really refactors anything... Feel free to unhold.

2022-03-18 15:43 UTC, acardace commented
> /approve /hold Can the commit title be adjusted? I wouldn't say this PR really refactors anything... Feel free to unhold.

sure, I was having doubts myself but was looking for a short title.

2022-03-18 15:47 UTC, acardace commented
/unhold
@maiqueb can you re-lgtm please?

2022-03-18 22:46 UTC, merged