tests: Set exact expectations on VirDomain.Free() call
kubevirt/kubevirt pull request #7700
Opened 2022-05-06 17:21 UTC by vasiliy-ul

**What this PR does / why we need it**:

The PR includes some refactoring and fixes for `virtwrap/manager` unit tests:
- avoid using `AnyTimes()` in expectation for `VirDomain.Free()` since that does not ensure that the call has been made
- migration abort internally spawns an async goroutine. Need to wait untill it finishes to avoid flaky behaviour in the tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

2022-05-09 07:14 UTC, rmohr commented
/cc @xpivarc 

related to the migration abort flakes.

2022-05-09 08:06 UTC, maiqueb requested changes
I think it is preferable to invoke `mockDomain.EXPECT().Free()` in a [defer cleanup](https://onsi.github.io/ginkgo/#cleaning-up-our-cleanup-code-defercleanup) - a ginkgov2 construct, since it would require less test changes.

2022-05-09 11:25 UTC, vasiliy-ul commented
> I think it is preferable to invoke `mockDomain.EXPECT().Free()` in a [defer cleanup](https://onsi.github.io/ginkgo/#cleaning-up-our-cleanup-code-defercleanup) - a ginkgov2 construct, since it would require less test changes.

Hi @maiqueb . Thank you for the suggestion. I am not sure I properly understood the idea. Could you elaborate more on how to apply `DeferCleanup` here?  For me this seems more like a way of cleaning up the test environment. With `mockDomain.EXPECT().Free()` its also tricky that it can be called multiple times depending on the ammount on lookups.

2022-05-09 11:48 UTC, maiqueb commented
> > I think it is preferable to invoke `mockDomain.EXPECT().Free()` in a [defer cleanup](https://onsi.github.io/ginkgo/#cleaning-up-our-cleanup-code-defercleanup) - a ginkgov2 construct, since it would require less test changes.
> 
> Hi @maiqueb . Thank you for the suggestion. I am not sure I properly understood the idea. Could you elaborate more on how to apply `DeferCleanup` here? For me this seems more like a way of cleaning up the test environment. With `mockDomain.EXPECT().Free()` its also tricky that it can be called multiple times depending on the ammount on lookups.

Thanks for the reply. You're right, I should have explained better what I meant... If I did, I wouldn't have ended up writing it :) 

IIUC - I might be missing something - we just have to ensure the `. Free()` function is invoked on the `mockDomain` struct. As such, I think it can be applied in the `BeforeEach` section, just like what's happening now for https://github.com/kubevirt/kubevirt/pull/7700/files#diff-cc87fdb7620d346748f3bf988430cc7365244cceab206c1617fa5b2ce32998d8R97 - but without the `AnyTimes`. Looking more carefully at the code I now realize I have no clue when this `Free` function has to be called - but I start to realize it may not be required for every test - which would make my suggestion harder. 

Regarding the `DeferCleanup` statement, I now realize it is semantically wrong - defining the expectations within something meant to perform cleanup is confusing. (I can't even justify my original intention ... sorry about that).

2022-05-09 11:59 UTC, vasiliy-ul commented
> IIUC - I might be missing something - we just have to ensure the `. Free()` function is invoked on the `mockDomain` struct. As such, I think it can be applied in the `BeforeEach` section, just like what's happening now for https://github.com/kubevirt/kubevirt/pull/7700/files#diff-cc87fdb7620d346748f3bf988430cc7365244cceab206c1617fa5b2ce32998d8R97 - but without the `AnyTimes`. Looking more carefully at the code I now realize I have no clue when this `Free` function has to be called - but I start to realize it may not be required for every test - which would make my suggestion harder.
> 

Yeah, unfortunately `mockDomain.EXPECT().Free()` cannot be called in `BeforeEach` since it requires exact quantification. Some tests may call it once, others - twice... others more or zero. That depends on the actual test case and how many times the corresponding domain lookup function has been called.

> Regarding the `DeferCleanup` statement, I now realize it is semantically wrong - defining the expectations within something meant to perform cleanup is confusing. (I can't even justify my original intention ... sorry about that).

NP. Thank you for raising this concern anyway. I previously did not know about `DeferCleanup`. It surely can be usefull in some situations :)

2022-10-10 12:09 UTC, xpivarc commented
/reopen
/remove-lifecycle rotten

2022-10-11 09:19 UTC, vasiliy-ul commented
Took a bit of time to come back to that PR. But now should be ready for review.

2023-03-13 07:21 UTC, xpivarc reviewed
/reopen
/approve
@vasiliy-ul Do you want to rebase?

2023-03-21 10:23 UTC, rmohr commented
/lgtm

2023-03-21 11:34 UTC, rmohr commented
/test pull-kubevirt-e2e-k3d-1.25-sriov

2023-03-22 11:28 UTC, vasiliy-ul commented
/retest-required

2023-03-22 15:17 UTC, merged