Set `clusterIP` field for kubevirt-prometheus-metrics service to `None`
kubevirt/kubevirt pull request #7762
Opened 2022-05-18 09:22 UTC by VirrageS

**What this PR does / why we need it**: `kubevirt-prometheus-metrics` Service must be created with `ClusterIP` set to `None`. If not, we end up creating a LoadBalancer rule with endpoints equal to number of nodes in the cluster. If we have a 1000-node cluster, then we will have a LB rule with 1000 endpoints. For more info see: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: None

**Special notes for your reviewer**: None

**Release note**:

```release-note
Service `kubevirt-prometheus-metrics` now sets `ClusterIP` to `None` to make it a headless service.
```

2022-06-08 17:50 UTC, VirrageS commented
/ok-to-test

2022-06-09 07:29 UTC, VirrageS commented
/retest

2022-06-12 14:59 UTC, VirrageS commented
/retest-required

2022-07-19 12:31 UTC, VirrageS commented
@maiqueb could you take a look?

2022-07-19 14:40 UTC, maiqueb requested changes
Code wise, I'm OK.

... but you need to add at least a unit test for this. Something that defines the expected behavior of the `kubevirt-prometheus-metrics` service to be a headless service.

Unfortunately, this pkg doesn't exhibit this good practice, but, if you don't mind (too much...) I would rather have you start it :)

2022-07-20 14:32 UTC, VirrageS commented
I've added a test, but not entirely sure what should I check more. Let me know if you have something specific in mind.

2022-07-20 14:39 UTC, maiqueb requested changes
You'll also need to update the bazel metadata (you've added a file); run `make deps-update` (and to be on the safe side also `make generate`), and commit those changes.

2022-07-21 06:07 UTC, VirrageS commented on pkg/virt-operator/resource/generate/components/deployments_test.go
> +		Expect(service.Spec.ClusterIP).To(Equal(corev1.ServiceTypeClusterIP))
Whoops, I've copied wrong variable. Sorry for that, I've fixed that and tests now pass.

2022-07-21 06:21 UTC, VirrageS commented
@maiqueb thanks for catching all of that. I've updated the MR. Let me know if there is something more to be done.

2022-07-21 08:08 UTC, maiqueb approved these changes
Thank you.

2022-07-21 08:15 UTC, VirrageS commented
/assign @vladikr

2022-08-21 15:16 UTC, VirrageS commented
@vladikr could you take a look?

2022-11-19 18:06 UTC, maiqueb commented
/remove-lifecycle stale

@xpivarc / @AlonaKaplan could you take a look into this ?

2022-12-01 11:33 UTC, xpivarc commented
/cc @sradco @Barakmor1

2022-12-05 10:41 UTC, VirrageS commented
@sradco @Barakmor1 could you take a look and approve if looks okay?

2022-12-05 10:44 UTC, Barakmor1 commented
/lgtm
Thank you

2022-12-05 16:01 UTC, VirrageS commented
/assign @vladikr

2022-12-06 10:39 UTC, VirrageS commented
/retest

2022-12-06 12:05 UTC, xpivarc commented
@VirrageS I am less confident in this area but I guess you want to optimize this. Prometheus will only use the endpoints for scrapping the data, is that right? (Meaning it does not need the static IP)
/test ?

2022-12-06 12:38 UTC, Barakmor1 commented
/hold
@VirrageS just few questions:
> we end up creating a LoadBalancer rule with endpoints equal to number of nodes in the cluster. If we have a 1000-node 
> cluster, then we will have a LB rule with 1000 endpoints. 
1) why would we have 1000 endpoints?
   I think that the number of endpoints will be equal to the number of pods backing the service

2) The LB will make sure we divide the service workload to all the pods, why do we need to remove it?

2022-12-06 12:49 UTC, VirrageS commented
> why would we have 1000 endpoints?
> I think that the number of endpoints will be equal to the number of pods backing the service
Yes, and I had in mind that we have 1000 nodes with `virt-handlers` running on them.

> The LB will make sure we divide the service workloads to all the pods, why do we need to remove it?
But why do you need to divide the workload if you don't have any workload? Prometheus need to ask each Pod individually, it doesn't send request to the Service itself. It uses Service to get all IPs of the Pods backing the Service. Otherwise, how the Prometheus would get the metrics from all the Pods? (if the load-balancer would be random it could be weeks until some specific Pod gets the request).

2022-12-06 12:54 UTC, Barakmor1 commented
> @Barakmor1
> 
> > why would we have 1000 endpoints?
> > I think that the number of endpoints will be equal to the number of pods backing the service
> 
> Yes, and I had in mind that we have 1000 nodes with 1000 `virt-handlers` running on them (each `virt-handler` on each node).
> 
> > The LB will make sure we divide the service workloads to all the pods, why do we need to remove it?
> 
> But why do you need to divide the workload if you don't have any workload? Prometheus need to ask each Pod individually, it doesn't send request to the Service itself. It uses Service to get all IPs of the Pods backing the Service. Otherwise, how the Prometheus would get the metrics from all the Pods? (if the load-balancer would be random it could be weeks until some specific Pod gets the request).

Got it Thank you for the explaination.
last question:
What happens now when we do have 1000 nodes in the cluster how does Prometheus get metrics from all the virt-handler pods?

2022-12-06 13:05 UTC, Barakmor1 commented
/unhold

2022-12-06 13:28 UTC, Barakmor1 commented
Maybe it would be better using PodMonitors 
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#using-podmonitors

2022-12-07 10:52 UTC, rmohr commented
/approve

2022-12-07 13:28 UTC, VirrageS commented
/test pull-kubevirt-e2e-k8s-1.25-sig-network

2022-12-07 14:55 UTC, merged

2022-12-09 08:48 UTC, rmohr commented
> I can explore that in follow-up MR. I would need to do the testing, I wasn't aware of `PodMonitor`s before.

Now with `None`, it should be equally efficient. I am not sure a switch is necessary.