e2e, istio: Wait for VMI to launch before Logging in
kubevirt/kubevirt pull request #8324
Opened 2022-08-19 07:49 UTC by rhrazdil

Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

**What this PR does / why we need it**:
This commit uses tests.RunVMIAndExpectLaunch function to
create VMI and wait for it to be running, before calling console.LoginToAlpine.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes flake: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7007/pull-kubevirt-e2e-k8s-1.22-sig-network/1559831970916077568

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2022-08-19 07:49 UTC, rhrazdil commented
/retest-required

2022-08-19 09:54 UTC, rhrazdil commented
/retest-required

2022-08-19 14:03 UTC, EdDev requested changes
This commit uses tests.RunVMIAndExpectLaunch function to
create VMI and wait for it to be running, before calling
console.LoginToAlpine.

This info is exactly what is seen in this change, I think it is redundant.
What I am missing here is the reasoning (e.g. flakes have been seen ....).
Could you please add that?

2022-08-19 14:20 UTC, rhrazdil commented on tests/network/vmi_istio.go
> +				By("Starting VirtualMachineInstance")
The By step? It's not necessary, but it helps localizes the place of failure, doesn't it?

2022-08-19 14:22 UTC, rhrazdil commented
>>This commit uses tests.RunVMIAndExpectLaunch function to
create VMI and wait for it to be running, before calling
console.LoginToAlpine.

>This info is exactly what is seen in this change, I think it is redundant.
What I am missing here is the reasoning (e.g. flakes have been seen ....).
Could you please add that?

Sure, updated the commit message to include the reasoning.

2022-08-19 14:32 UTC, EdDev commented on tests/network/vmi_istio.go
> +				By("Starting VirtualMachineInstance")
When it fails, I would expect to see the failure in the error/assertion.

a log for each action is not helpful IMO. I would prefer to have less of those, replacing them with proper errors.

2022-08-19 14:35 UTC, EdDev approved these changes
Thanks!

I do not like the logging overuse, but it is not worth blocking this change on it.

2022-08-22 12:31 UTC, AlonaKaplan commented
/approve

2022-08-22 13:21 UTC, rhrazdil commented
/retest-required

2022-08-23 03:17 UTC, merged