Fix remoteAddress field being truncated when it is an ipv6 address
kubevirt/kubevirt pull request #8660
Opened 2022-10-25 02:57 UTC by huyinhou

when deploy the kubevirt in an ipv6-only cluster, the remoteAddress field in virt-api rest log is truncated, which looks like `{"component":"virt-api","contentLength":2677,..."remoteAddress":"[fd00",` 
so we use the `net.SplitHostPort` to split the host and port, then log the real host in remoteAddress field.

Signed-off-by: huyinhou <huyinhou@bytedance.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2022-10-25 11:14 UTC, lyarwood commented
/ok-to-test

2022-10-26 07:33 UTC, huyinhou commented
/retest-required

2022-10-26 12:05 UTC, lyarwood requested changes

2022-10-26 12:05 UTC, lyarwood commented on pkg/rest/filter/filter.go
> +	"net"
Can you manually update the associated [BUILD.bazel](https://github.com/kubevirt/kubevirt/blob/10239eacdbdae4dd896c6adabab5115e5c62e3cf/pkg/rest/filter/BUILD.bazel) file or run `make generate` adding the changes to this PR?

2022-11-15 15:01 UTC, huyinhou commented
/retest-required

2022-12-09 12:07 UTC, maya-r commented
/lgtm

2022-12-19 11:27 UTC, xpivarc reviewed
/approve

2022-12-21 00:06 UTC, merged