virtctl: Allow to infer [instancetype|preference] when creating a VM
kubevirt/kubevirt pull request #9085
Opened 2023-01-23 15:54 UTC by 0xFelix

**What this PR does / why we need it**:

This adds the flags --infer-instancetype and --infer-preference.
When specified the instancetype and/or preference to be used are inferred
from the first volume of a created VM. The flags are mutually exclusive to
the --instancetype respectively --preference flag.

**Release note**:

```release-note
virtctl: Add options to infer instancetype and preference when creating a VM
```

2023-01-23 15:56 UTC, 0xFelix commented
/cc @lyarwood

2023-01-23 16:35 UTC, lyarwood requested changes
LGTM overall I just want to surface the ordering of `Volumes` in the user visible help text so they can understand why they always see a `DataSource` picked ahead of a `PVC` etc.

2023-01-23 16:35 UTC, lyarwood commented on pkg/virtctl/create/vm.go
> +  # Create a manifest for a VirtualMachine with a cloned DataSource and an inferred preference
supernit - could just be one example here with both flags

2023-01-23 16:35 UTC, lyarwood commented on pkg/virtctl/create/vm.go
> +// Containerdisk < DataSource < Clone PVC < PVC
Can you add this ordering of `Volumes` to the user visible help for each flag?

2023-01-23 16:53 UTC, lyarwood commented
@davidvossel FYI we are trying to sneak support for `InferFromVolume` into `virtctl` for `v0.59.0`. Hopefully straight forward but your thoughts and review are welcome if you have time.

2023-01-24 08:02 UTC, 0xFelix commented
@lyarwood Addressed both comments.

2023-01-24 09:36 UTC, lyarwood commented
/lgtm

Thanks!

2023-01-24 12:38 UTC, 0xFelix commented
/retests

2023-01-24 12:38 UTC, 0xFelix commented
/retest

2023-01-24 15:39 UTC, 0xFelix commented
/retest

2023-01-25 10:41 UTC, lyarwood commented
/retest

2023-01-25 14:17 UTC, davidvossel reviewed
/approve

2023-01-26 07:54 UTC, lyarwood commented
/retest

2023-01-26 08:52 UTC, merged