Migrate from k8s.gcr.io to registry.k8s.io
kubevirt/kubevirt pull request #9262
Opened 2023-02-17 06:18 UTC by RishabhKodes

**What this PR does / why we need it**:
This PR is part of the Umbrella issue, https://github.com/kubernetes/k8s.io/issues/4780

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/k8s.io/issues/4780

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2023-02-18 03:59 UTC, LinuxSuRen requested changes
Thanks for your contributions. But all these files are generated. Is that possible to update the upstream tool, and re-generate them?

2023-02-19 10:28 UTC, iholder101 commented
Hey @RishabhKodes! Thanks for this PR!

> Thanks for your contributions. But all these files are generated. Is that possible to update the upstream tool, and re-generate them?

+1

Can you please also update the release notes on the PR description (or set it to `NONE`) to remove the `do-not-merge/release-note-label-needed` label? Thanks!

2023-02-19 11:19 UTC, RishabhKodes commented
> Hey @RishabhKodes! Thanks for this PR!
> 
> > Thanks for your contributions. But all these files are generated. Is that possible to update the upstream tool, and re-generate them?
> 
> +1
> 
> Can you please also update the release notes on the PR description (or set it to `NONE`) to remove the `do-not-merge/release-note-label-needed` label? Thanks!

Hey @iholder101, updated the release notes.

2023-02-22 20:07 UTC, RishabhKodes commented
Hi @iholder101, are there any other changes required on this pr?

2023-02-23 07:44 UTC, iholder101 commented
> Hi @iholder101, are there any other changes required on this pr?

Hi @RishabhKodes! Thanks again for the contribution.

As mentioned in [this comment](https://github.com/kubevirt/kubevirt/pull/9262#pullrequestreview-1304473054) above, the files you've changed are auto-generated (like every file that ends with `_generated.go`). These files aren't meant to be changed directly, but by executing `make generate`.

I see there are two kinds of files that you've changed:
Firstly, files under the `/vendor` directory are usually dependencies that are outside of Kubevirt's code, like `vendor/k8s.io/api/core/v1/types.go` that you've changed for example is Kubernetes' code, not Kubevirt's. So to change these the code needs to change at their side and we would get it once upgrading.

Secondly, there are files that are generated by `make generate`. CI would fail if you change these files directly. In this case TBH I'm not sure where `k8s.gcr.io` even comes from, maybe it's an openapi configuration / they need to update it on their side? Maybe @dhiller knows?

Thanks again for you contribution.

2023-02-23 19:59 UTC, RishabhKodes commented
@dhiller can you provide some insight on this, please? Thanks

2023-02-24 13:53 UTC, xpivarc commented
Thank you for reaching out. I believe this is not necessary. But it is worth to ping following people:
@AlonaKaplan Seems like https://github.com/kubevirt/kubesecondarydns is using k8s.gcr.io and you need to migrate.
@phoracek Seems like https://github.com/kubevirt/cluster-network-addons-operator have some mention in version 83. Please check it out.
@awels  Seems like https://github.com/kubevirt/csi-driver has some reference and you need to migrate.

2023-02-24 17:54 UTC, RishabhKodes commented
> Thank you for reaching out. I believe this is not necessary. But it is worth to ping following people: @AlonaKaplan Seems like https://github.com/kubevirt/kubesecondarydns is using k8s.gcr.io and you need to migrate. @phoracek Seems like https://github.com/kubevirt/cluster-network-addons-operator have some mention in version 83. Please check it out. @awels Seems like https://github.com/kubevirt/csi-driver has some reference and you need to migrate.

Thanks for mentioning @xpivarc, will create pr's for these repos as well. Tagging you in them as well PTAL.

2023-03-10 05:34 UTC, closed without merging