[DRAFT]: add legacy fields to cloudinit configdrive metadata struct
kubevirt/kubevirt pull request #9390
Opened 2023-03-08 15:22 UTC by alaypatel07

This allows for upgrades from older version on kubevirt to work. Without this patch the applications baked into the VMI image that depend on the metadata fields of the cloudinit metadata json will be broken upon upgrade

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2023-03-08 21:04 UTC, rthallisey commented
/ok-to-test

2023-03-09 06:03 UTC, EdDev requested changes
I'm sorry, but I think there is not enough justification to keep backward compatibility with such an old version (0.35) and with only a few (one?) incident of this breaking a user.

If we will take such a policy to always keep backward compatibility forever, we would not have a chance to evolve without a high maintenance burden.

We are also not supporting an upgrade between 0.35 to the latest master, so I am not even sure how this will help in a wider view of this solution.

Also, by adding this fields, we actually hint users that they can be used which is also a problem.

Ref: https://github.com/kubevirt/kubevirt/issues/9292#issuecomment-1461331382

2023-03-09 13:02 UTC, alaypatel07 commented
> I'm sorry, but I think there is not enough justification to keep backward compatibility with such an old version (0.35) and with only a few (one?) incident of this breaking a user.
> 
> If we will take such a policy to always keep backward compatibility forever, we would not have a chance to evolve without a high maintenance burden.

Commented on the original thread, it's not just about backward compat. The its also about inconsistency of metadata rendered inside the cloud-init metadata (depending on which source metadata.json is coming from) which the application needs to be aware of.

2023-03-09 14:53 UTC, rthallisey commented
> I'm sorry, but I think there is not enough justification to keep backward compatibility with such an old version (0.35) and with only a few (one?) incident of this breaking a user.
>
> If we will take such a policy to always keep backward compatibility forever, we would not have a chance to evolve without a high maintenance burden.
>
You're highlighting an important problem, but the bigger problem is that there isn't a well defined policy.  What Alay is describing is that this change broke backwards compatibility and there wasn't a warning saying, "this is deprecated and will be removed in version x.y.z".  And that's not anyone's fault because there isn't a well-defined policy the community is enforcing.

I think the ask here is to continue carrying the backwards compatible change until the community properly deprecates it.

> Also, by adding this fields, we actually hint users that they can be used which is also a problem.
>
You're hitting the nail on the head on why there needs to be a community enforced policy.  We don't want to break users, so inform them about an upcoming breaking change.

2023-03-09 17:35 UTC, alaypatel07 commented
> You're highlighting an important problem, but the bigger problem is that there isn't a well defined policy. What Alay is describing is that this change broke backwards compatibility and there wasn't a warning saying, "this is deprecated and will be removed in version x.y.z". And that's not anyone's fault because there isn't a well-defined policy the community is enforcing.

+1, I agree I couldnt find a policy for such a case. I have proposed a potential policy on this PR https://github.com/kubevirt/kubevirt/issues/9292#issuecomment-1462011393 may be we can move the discussion there.

> Also, by adding this fields, we actually hint users that they can be used which is also a problem. 

In addition to the policy, I do want to highlight that while this is a good first example of such scenario, the current behavior of the API results in inconsistent metadata json rendered by cloud-init depending on the source. So having both the fields is not potentially problem, it could be desired for making the applications in the VMI image platform independent.

2023-03-09 20:22 UTC, EdDev commented
> You're highlighting an important problem, but the bigger problem is that there isn't a well defined policy. What Alay is describing is that this change broke backwards compatibility and there wasn't a warning saying, "this is deprecated and will be removed in version x.y.z". And that's not anyone's fault because there isn't a well-defined policy the community is enforcing.
>
> I think the ask here is to continue carrying the backwards compatible change until the community properly deprecates it.

We are actually, per my experience in this project, are spending a lot of effort in keeping backward compatability and making sure things are communicating before a deprecation occurs.
This has been a non official norm to do this and it is the case now.

Arguing that the fact this policy does not exist officially may at the same time also be interpreted that there is no guarantee API/s won't break. But again, maintainers are pedantic in keeping this non-breaking norm.
That said, something that happened 3 years ago on a version we long ago do not support, cannot be, in my view, a strong reason to add this thing back in. It has implications on other such requests which can come in.

To be clear, I am in favor of formalizing a policy, no arguments there.

> > Also, by adding this fields, we actually hint users that they can be used which is also a problem.
> 
> You're hitting the nail on the head on why there needs to be a community enforced policy. We don't want to break users, so inform them about an upcoming breaking change.

And we do so in most cases.
If we have some misses, it is a mistake.
But asking to fix an upgrade path from such an old version is not reasonable IMO.
Will we do so also for versions 4 and 5 years old? Where does it end?

We do not want to break users, but we also cannot support 2 or 3 years old versions.
Introducing this back in, puts back the burden on the kubevirt community to deprecate it once more and support this flow for a few versions.

In the end, the project is governed by maintainers. If maintainers that own & support this API agree, it will get in.
I just hope they take into account the pros and cons discussed here.
I also hope there will be a wide agreement on this as it affects multiple SIGs.

2023-03-15 08:30 UTC, rmohr requested changes
I think we have a pretty easy way to keep the legacy fields without much maintenance burden. Ok for me to add.

2023-03-15 16:13 UTC, alaypatel07 commented
/retitle add custom json marshaller for legacy fields in cloudinit ConfigDriveMetadata struct

2023-03-15 20:12 UTC, alaypatel07 commented
```
[alayp@alaypfedora kubevirt]$ make test
..
..
<output-snipped>
[
//pkg/virtctl/vmexport:go_default_test                                   PASSED in 0.1s
//pkg/watchdog:go_default_test                                           PASSED in 0.2s
//staging/src/kubevirt.io/client-go/api:go_default_test                  PASSED in 0.6s
//staging/src/kubevirt.io/client-go/kubecli:go_default_test              PASSED in 0.5s
//staging/src/kubevirt.io/client-go/log:go_default_test                  PASSED in 0.4s
//tests/framework/matcher:go_default_test                                PASSED in 0.1s

Executed 131 out of 131 tests: 131 tests pass.
INFO: Build completed successfully, 5842 total actions
[alayp@alaypfedora kubevirt]$ git status
On branch cloud-init-metadata-legacy-fields
Your branch is up to date with 'alaypatel07/cloud-init-metadata-legacy-fields'.

nothing to commit, working tree clean
[alayp@alaypfedora kubevirt]$
```

not sure why the unit tests failed, local runs seem to be passing

/test pull-kubevirt-unit-test

2023-03-16 08:34 UTC, rmohr commented
/retest

2023-03-16 12:26 UTC, alaypatel07 commented
/test pull-kubevirt-e2e-k8s-1.25-ipv6-sig-network

2023-03-16 14:03 UTC, alaypatel07 commented
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9435/pull-kubevirt-e2e-k8s-1.25-sig-network/1635981051517997056
```
Tests Suite: [sig-network] nic-hotplug a stopped VM cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user 
```


[https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9390/[…]-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1636089331363876864](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9390/pull-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1636089331363876864)
```
Tests Suite: [sig-network] nic-hotplug a stopped VM cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user
```
[https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9435/[…]-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1635981044890996736](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9435/pull-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1635981044890996736)
```
Tests Suite: [sig-network] nic-hotplug a stopped VM cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user 
```

[https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9420/[…]-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1635968696641916928](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9420/pull-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1635968696641916928)
```
Tests Suite: [sig-network] nic-hotplug a stopped VM cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user
```

The network hotplug test seems to be failing sporadically. I am not sure if there is already an issue tracking

2023-03-16 14:58 UTC, xpivarc commented
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9435/pull-kubevirt-e2e-k8s-1.25-sig-network/1635981051517997056
> 
> ```
> Tests Suite: [sig-network] nic-hotplug a stopped VM cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user 
> ```
> 
> [https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9390/[…]-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1636089331363876864](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9390/pull-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1636089331363876864)
> 
> ```
> Tests Suite: [sig-network] nic-hotplug a stopped VM cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user
> ```
> 
> [https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9435/[…]-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1635981044890996736](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9435/pull-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1635981044890996736)
> 
> ```
> Tests Suite: [sig-network] nic-hotplug a stopped VM cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user 
> ```
> 
> [https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9420/[…]-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1635968696641916928](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9420/pull-kubevirt-e2e-k8s-1.25-ipv6-sig-network/1635968696641916928)
> 
> ```
> Tests Suite: [sig-network] nic-hotplug a stopped VM cannot be subject to **hot** plug, but will mutate the template.Spec on behalf of the user
> ```
> 
> The network hotplug test seems to be failing sporadically. I am not sure if there is already an issue tracking

@maiqueb FYI, can you charm in?

2023-08-13 17:33 UTC, closed without merging