Add virtctl create preference command
kubevirt/kubevirt pull request #9420
Opened 2023-03-13 15:57 UTC by opokornyy

**What this PR does / why we need it**:

This PR adds virtctl create preference command. This implementation does not cover all parameters that can be defined in a VirtualMachinePreference. Instead, it can be used as a starting point for users to streamline the creation of their own VirtualMachinePreference specifications.

**Special notes for your reviewer**:

**Release note**:
```None

```

2023-03-13 15:57 UTC, opokornyy commented
/cc @0xFelix @lyarwood

2023-03-14 07:55 UTC, 0xFelix reviewed
Added comments about two nits.

2023-03-14 07:55 UTC, 0xFelix commented on pkg/virtctl/create/preference/preference.go
> +	if c.cpu != string(instancetypev1alpha2.PreferCores) && c.cpu != string(instancetypev1alpha2.PreferSockets) && c.cpu != string(instancetypev1alpha2.PreferThreads) {
Can you make it span multiple lines so it is easier to read?

2023-03-14 07:55 UTC, 0xFelix commented on pkg/virtctl/create/preference/preference_test.go
> +		DescribeTable("should succeed with defined volume", func(namespacedFlag, volumeParam string, namespaced bool) {
Add test case for succeed without any flags?

2023-03-14 07:56 UTC, 0xFelix commented
Also, it looks like you need to update the bazel files (`make format` / `make generate`).

2023-03-15 08:10 UTC, opokornyy commented
/retest

2023-03-15 11:19 UTC, 0xFelix commented on pkg/virtctl/create/preference/preference.go
> +	cmd.Flags().BoolVar(&c.namespaced, NamespacedFlag, false, "Specify if VirtualMachinePreference should be created. By default VirtualMachineClusterPreference is created.")
Use `c.namespaced` as default here for consistency?

2023-03-15 11:19 UTC, 0xFelix commented on pkg/virtctl/create/preference/preference.go
> +	DeviceValueErr = "Device must have a value specified"
Unused?

2023-03-15 11:19 UTC, 0xFelix commented on pkg/virtctl/create/preference/preference.go
> +	NameErr        = "name must be specified"
Unused?

2023-03-16 08:11 UTC, opokornyy commented
/retest

2023-03-16 09:30 UTC, lyarwood requested changes
Mostly LGTM now but I'd like to see if we could be a little more explicit with the naming of the current switches assuming we don't want to allow sub-options in the future?

2023-03-16 09:30 UTC, lyarwood commented on pkg/virtctl/create/preference/preference.go
> +	VolumeFlag     = "volume"
I'm not sure about this flag name tbh, you're using it to define the storage class of a volume. `volume-storage-class`?

2023-03-16 09:30 UTC, lyarwood commented on pkg/virtctl/create/preference/preference.go
> +	CPUFlag        = "cpu"
IMHO this could be more specific if we aren't allowing sub options for these switches. `cpu-topology`?

2023-03-16 09:30 UTC, lyarwood commented on pkg/virtctl/create/preference/preference.go
> +	MachineFlag    = "machine"
As above, `machine-type`?

2023-03-16 09:39 UTC, lyarwood commented on pkg/virtctl/create/preference/preference.go
> +	}
I also wonder if we could get away with stashing logic like this alongside the constants? Something for a follow up however.

https://github.com/kubevirt/kubevirt/blob/91a4ac2114873d3102a558372920327c0c0ccd01/staging/src/kubevirt.io/api/instancetype/v1alpha2/types.go#L253-L263

2023-03-16 14:49 UTC, opokornyy commented
/retest

2023-03-17 14:55 UTC, 0xFelix commented
/lgtm

Thanks!

2023-03-20 14:32 UTC, enp0s3 commented on tests/virtctl/create_preference.go
> +		if clusterPreference != nil {
Where does the namespaced VMPs are deleted? Perhaps you need to clean them in [`CleanNamespaces()`](https://github.com/kubevirt/kubevirt/blob/3bee1de7b4f8bab059817cf44d636d2521dec8a9/tests/testsuite/namespace.go#L73)

2023-03-20 17:41 UTC, enp0s3 commented
@opokornyy I would suggest you to use dry-run also for the namespaced scope, since the namespaces are being re-used and deleted only at the end of the whole suite, this means you will have leftovers, which may introduce noise to the k8s reporter when a test fails.

2023-03-20 17:45 UTC, enp0s3 commented
/approve

2023-03-20 18:04 UTC, lyarwood commented
/lgtm

2023-03-21 07:05 UTC, enp0s3 commented
/lgtm

2023-03-21 12:36 UTC, merged