Remove "all" category from virtualmachineclusterinstancetypes/preferences
kubevirt/kubevirt pull request #9536
Opened 2023-03-29 13:22 UTC by akalenyu

**What this PR does / why we need it**:
This results in `k get all -n <namespace>` returning those cluster-scoped resources.
```bash
$ oc get all -n openshift-config
Warning: kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
NAME                                                                                AGE
virtualmachineclusterinstancetype.instancetype.kubevirt.io/cx1.2xlarge              5d22h
virtualmachineclusterinstancetype.instancetype.kubevirt.io/cx1.4xlarge              5d22h
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2177763

**Special notes for your reviewer**:

**Release note**:

```release-note
BugFix: virtualmachineclusterinstancetypes/preferences show up for get all -n <namespace>
```

2023-03-29 13:22 UTC, akalenyu commented
/cc @lyarwood

2023-03-29 15:21 UTC, lyarwood requested changes
/area instancetype 

I don't think this is correct, it drops the cluster wide resources from `get all -A` that we really don't want.

There has to be something else causing these resources to show up in the namespace, I'll try to look deeper now.

```
./cluster-up/kubectl.sh apply -f https://k8s.io/examples/admin/namespace-dev.yaml
./cluster-up/kubectl.sh apply -f examples/csmall.yaml -f examples/vm-cirros-csmall.yaml -n development
[..]
./cluster-up/kubectl.sh kustomize https://github.com/kubevirt/common-instancetypes.git | ./cluster-up/kubectl.sh apply -f -
[..]
./cluster-up/kubectl.sh get all -n development
selecting docker as container runtime
Warning: kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
NAME                                          AGE   STATUS    READY
virtualmachine.kubevirt.io/vm-cirros-csmall   35s   Stopped   False

NAME                                                         AGE
virtualmachineinstancetype.instancetype.kubevirt.io/csmall   35s

./cluster-up/kubectl.sh get all -A
selecting docker as container runtime
Warning: kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
NAMESPACE     NAME                                                READY   STATUS      RESTARTS   AGE
cdi           pod/cdi-apiserver-5b77c7f5bf-6s6jb                  1/1     Running     0          6m13s
cdi           pod/cdi-deployment-855f498c58-p2269                 1/1     Running     0          6m1s
cdi           pod/cdi-operator-f8bbdf8c5-fwncj                    1/1     Running     0          9m57s
cdi           pod/cdi-uploadproxy-d6ccf-vm2tj                     1/1     Running     0          6m1s
default       pod/local-volume-provisioner-8wlmv                  1/1     Running     0          11m
default       pod/snapshot-controller-0                           1/1     Running     0          11m
kube-system   pod/calico-kube-controllers-7bbc78ddf7-7c4g8        1/1     Running     0          11m
kube-system   pod/calico-node-f962h                               1/1     Running     0          11m
kube-system   pod/coredns-659bb6b7c8-chcx5                        1/1     Running     0          11m
kube-system   pod/coredns-659bb6b7c8-t5vr9                        1/1     Running     0          11m
kube-system   pod/etcd-node01                                     1/1     Running     1          11m
kube-system   pod/kube-apiserver-node01                           1/1     Running     1          11m
kube-system   pod/kube-controller-manager-node01                  1/1     Running     1          11m
kube-system   pod/kube-proxy-f4m8n                                1/1     Running     0          11m
kube-system   pod/kube-scheduler-node01                           1/1     Running     1          11m
kubevirt      pod/disks-images-provider-92wrw                     1/1     Running     0          6m24s
kubevirt      pod/virt-api-69d749dfd8-87pds                       1/1     Running     0          5m49s
kubevirt      pod/virt-controller-cc47d4f46-kfrrn                 1/1     Running     0          5m24s
kubevirt      pod/virt-controller-cc47d4f46-shx6n                 1/1     Running     0          5m24s
kubevirt      pod/virt-handler-r25lz                              1/1     Running     0          5m24s
kubevirt      pod/virt-operator-84997889cb-hfzrr                  1/1     Running     0          6m23s
kubevirt      pod/virt-operator-84997889cb-lk5tt                  1/1     Running     0          6m23s
rook-ceph     pod/csi-cephfsplugin-gmvtl                          3/3     Running     0          11m
rook-ceph     pod/csi-cephfsplugin-provisioner-5846cb8f8d-hr2lp   6/6     Running     0          11m
rook-ceph     pod/csi-rbdplugin-provisioner-984b4cddb-n82c9       6/6     Running     0          11m
rook-ceph     pod/csi-rbdplugin-zxz84                             3/3     Running     0          11m
rook-ceph     pod/rook-ceph-mgr-a-5dd6cd6f7d-qwg6v                1/1     Running     0          10m
rook-ceph     pod/rook-ceph-mon-a-8684459866-vdsh2                1/1     Running     0          11m
rook-ceph     pod/rook-ceph-operator-67b9bd5f47-d976t             1/1     Running     0          11m
rook-ceph     pod/rook-ceph-osd-0-54856f699-rhxw5                 1/1     Running     0          10m
rook-ceph     pod/rook-ceph-osd-prepare-node01-rmmzc              0/1     Completed   0          10m

NAMESPACE     NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
cdi           service/cdi-api                       ClusterIP   10.96.191.180    <none>        443/TCP                  9m45s
cdi           service/cdi-prometheus-metrics        ClusterIP   10.105.95.80     <none>        8080/TCP                 9m41s
cdi           service/cdi-uploadproxy               ClusterIP   10.108.11.173    <none>        443/TCP                  9m39s
cdi           service/cdi-uploadproxy-nodeport      NodePort    10.103.141.124   <none>        443:31001/TCP            6m24s
default       service/kubernetes                    ClusterIP   10.96.0.1        <none>        443/TCP                  11m
kube-system   service/kube-dns                      ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   11m
kubevirt      service/kubevirt-operator-webhook     ClusterIP   10.100.175.124   <none>        443/TCP                  5m52s
kubevirt      service/kubevirt-prometheus-metrics   ClusterIP   None             <none>        443/TCP                  5m52s
kubevirt      service/virt-api                      ClusterIP   10.97.212.42     <none>        443/TCP                  5m52s
kubevirt      service/virt-exportproxy              ClusterIP   10.101.58.115    <none>        443/TCP                  5m52s
rook-ceph     service/csi-cephfsplugin-metrics      ClusterIP   10.108.158.72    <none>        8080/TCP,8081/TCP        11m
rook-ceph     service/csi-rbdplugin-metrics         ClusterIP   10.106.129.30    <none>        8080/TCP,8081/TCP        11m
rook-ceph     service/rook-ceph-mgr                 ClusterIP   10.109.153.74    <none>        9283/TCP                 10m
rook-ceph     service/rook-ceph-mgr-dashboard       ClusterIP   10.101.33.185    <none>        7000/TCP                 10m
rook-ceph     service/rook-ceph-mon-a               ClusterIP   10.99.170.93     <none>        6789/TCP,3300/TCP        11m

NAMESPACE     NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
default       daemonset.apps/local-volume-provisioner   1         1         1       1            1           <none>                   11m
kube-system   daemonset.apps/calico-node                1         1         1       1            1           kubernetes.io/os=linux   11m
kube-system   daemonset.apps/kube-proxy                 1         1         1       1            1           kubernetes.io/os=linux   11m
kubevirt      daemonset.apps/disks-images-provider      1         1         1       1            1           <none>                   6m24s
kubevirt      daemonset.apps/virt-handler               1         1         1       1            1           kubernetes.io/os=linux   5m24s
rook-ceph     daemonset.apps/csi-cephfsplugin           1         1         1       1            1           <none>                   11m
rook-ceph     daemonset.apps/csi-rbdplugin              1         1         1       1            1           <none>                   11m

NAMESPACE     NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
cdi           deployment.apps/cdi-apiserver                  1/1     1            1           9m45s
cdi           deployment.apps/cdi-deployment                 1/1     1            1           9m41s
cdi           deployment.apps/cdi-operator                   1/1     1            1           9m57s
cdi           deployment.apps/cdi-uploadprox [...]

2023-03-29 16:10 UTC, akalenyu commented
> /area instancetype
> 
> I don't think this is correct, it drops the cluster wide resources from `get all -A` that we really don't want.
> 
> There has to be something else causing these resources to show up in the namespace, I'll try to look deeper now.

Yeah not sure what is the right way to go about this, did not consider `get all -A`.
but we are definitely outnumbered
```bash
$ oc api-resources --namespaced=false -o name | wc -l
143
$ ./script.sh 
virtualmachineclusterinstancetypes.instancetype.kubevirt.io
virtualmachineclusterpreferences.instancetype.kubevirt.io
migrationpolicies.migrations.kubevirt.io
configs.operator.openshift.io
consoles.operator.openshift.io
```

2023-03-30 10:56 UTC, akalenyu commented
> > /area instancetype
> > I don't think this is correct, it drops the cluster wide resources from `get all -A` that we really don't want.
> > There has to be something else causing these resources to show up in the namespace, I'll try to look deeper now.
> 
> Yeah not sure what is the right way to go about this, did not consider `get all -A`. but we are definitely outnumbered
> 
> ```shell
> $ oc api-resources --namespaced=false -o name | wc -l
> 143
> $ ./script.sh 
> virtualmachineclusterinstancetypes.instancetype.kubevirt.io
> virtualmachineclusterpreferences.instancetype.kubevirt.io
> migrationpolicies.migrations.kubevirt.io
> ```

Sorry we're even more outnumbered, just these 3 kv crds

2023-04-04 16:44 UTC, lyarwood commented
/lgtm

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#rules-for-extending-special-resource-alias---all

Finally found some documentation about all (no pun intended) of this and it does highlight that cluster-level resources shouldn't be part of this category.

I've got some supernits around the commit subject and releasenote but I'm okay with this now otherwise. Can you update both to something like the following if you get a chance? 

`bugfix: Remove all category from VirtualMachineCluster{Instancetype,Preference} CRDs`

2023-04-04 16:45 UTC, lyarwood commented
Forgot to say that you could likely handle `migrationpolicy` in a follow up as well either as part of this PR or a new one.

2023-04-05 15:00 UTC, lyarwood commented
/cherrypick release-0.59

2023-04-05 18:18 UTC, lyarwood commented
/retest-required

2023-04-06 01:58 UTC, merged