affine kvm-pit kernel thread to vcpu-0 cpumask
kubevirt/kubevirt pull request #9613
Opened 2023-04-14 15:51 UTC by matosatti

**What this PR does / why we need it**:
Certain use-cases rely on injection of PIT interrupts to the guest in a timely fashion. Today, the kvm-pit kernel thread which is responsible for emulating PIT interrupts runs on housekeeping cores, sharing time with other kubernetes threads (such as kubelet). This has been found to be a problem for a particular workload requiring timely PIT interrupts (see trace below). The fix is to affine kvm-pit kernel thread to the same cpu as vcpu-0, when dedicated cpu placement is enabled in the guest configuration.

          <idle>-0     [000] d.h. 102470.847586: hrtimer_expire_entry: hrtimer=00000000e3dea339 function=pit_timer_fn [kvm] now=102463903132805
          <idle>-0     [000] d.h. 102470.847587: sched_waking: comm=kvm-pit/67 pid=1212317 prio=120 target_cpu=001
          <idle>-0     [001] d... 102470.847590: sched_switch: prev_comm=swapper/1 prev_pid=0 prev_prio=120 prev_state=S ==> next_comm=kvm-pit/67 next_pid=1212317 next_prio=120
      kvm-pit/67-1212317 [001] d... 102470.847594: sched_switch: prev_comm=kvm-pit/67 prev_pid=1212317 prev_prio=120 prev_state=D ==> next_comm=swapper/1 next_pid=0 next_prio=120
       CPU 0/KVM-1212312 [006] d... 102470.847596: kvm_entry: vcpu 0, rip 0x35fd
       CPU 0/KVM-1212312 [006] d... 102470.847597: kvm_exit: vcpu 0 reason EOI_INDUCED rip 0x1bab info1 0x0000000000000022 info2 0x0000000000000000 intr_info 0x00000000 error_code 0x00000000
       CPU 0/KVM-1212312 [006] d... 102470.847598: kvm_entry: vcpu 0, rip 0x1bab
...
       CPU 0/KVM-1212312 [006] d... 102470.847622: kvm_exit: vcpu 0 reason HLT rip 0x35fc info1 0x0000000000000000 info2 0x0000000000000000 intr_info 0x00000000 error_code 0x00000000
           <...>-64244 [000] d.h. 102470.857590: hrtimer_expire_entry: hrtimer=00000000e3dea339 function=pit_timer_fn [kvm] now=102463913135899
           <...>-64244 [000] d.h. 102470.857599: sched_waking: comm=kvm-pit/67 pid=1212317 prio=120 target_cpu=001
  kube-apiserver-64649 [004] d.h. 102470.860004: hrtimer_expire_entry: hrtimer=00000000f5450c52 function=pit_timer_fn [kvm] now=102463915550678
           <...>-64245 [003] d.h. 102470.863029: hrtimer_expire_entry: hrtimer=000000004736fe96 function=pit_timer_fn [kvm] now=102463918575518
           <...>-64244 [000] d.h. 102470.867587: hrtimer_expire_entry: hrtimer=00000000e3dea339 function=pit_timer_fn [kvm] now=102463923133350
           <...>-64244 [000] d.h. 102470.869780: hrtimer_expire_entry: hrtimer=000000005deb41ca function=pit_timer_fn [kvm] now=102463925326017
           <...>-64244 [000] d... 102470.877465: sched_switch: prev_comm=kube-apiserver prev_pid=64244 prev_prio=120 prev_state=S ==> next_comm=kvm-pit/67 next_pid=1212317 next_prio=120
      kvm-pit/67-1212317 [000] d... 102470.877483: sched_switch: prev_comm=kvm-pit/67 prev_pid=1212317 prev_prio=120 prev_state=D ==> next_comm=cluster-policy- next_pid=60163 next_prio=120
       CPU 0/KVM-1212312 [006] d... 102470.877486: kvm_entry: vcpu 0, rip 0x35fd
       CPU 0/KVM-1212312 [006] d... 102470.877490: kvm_exit: vcpu 0 reason EOI_INDUCED rip 0x1bab info1 0x0000000000000022 info2 0x0000000000000000 intr_info 0x00000000 error_code 0x00000000
       CPU 0/KVM-1212312 [006] d... 102470.877491: sched_waking: comm=kvm-pit/67 pid=1212317 prio=120 target_cpu=000
       CPU 0/KVM-1212312 [006] d... 102470.877494: kvm_entry: vcpu 0, rip 0x1bab

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2023-04-14 20:21 UTC, vladikr commented
/ok-to-test

2023-04-17 18:01 UTC, matosatti commented
/retest

2023-04-19 17:46 UTC, vladikr commented
/retest

2023-04-26 12:32 UTC, vladikr commented on pkg/virt-handler/vm.go
> +	fpath := "/proc/" + strconv.Itoa(vmpid) + "/status"
could you please use filepath.Join ?

2023-04-26 12:42 UTC, vladikr commented on pkg/virt-handler/vm.go
> +func get_nspid(vmpid int, vmi *v1.VirtualMachineInstance) (int, error) {
Can you please add more details as to what does this function gets?

2023-04-26 12:46 UTC, vladikr commented on pkg/virt-handler/vm.go
> +	}
:+1:

2023-04-26 18:43 UTC, matosatti commented on pkg/virt-handler/vm.go
> +	}
@vladikr hopefully all of your comments have been addressed.

2023-04-27 10:59 UTC, matosatti commented
/retest

2023-04-28 17:54 UTC, vladikr commented
Thanks @matosatti ! 
/approve

@acardace could you please take a look?

2023-05-02 08:07 UTC, xpivarc requested changes
Few nits inline

2023-05-02 08:07 UTC, xpivarc commented on pkg/virt-handler/isolation/isolation.go
> +	KvmPitPid(vmpid int, vmi *v1.VirtualMachineInstance) (int, error)
`vmpid` seems to be not required as argument as you can just call `GetQEMUProcess` inside `KvmPitPid`

2023-05-02 08:07 UTC, xpivarc commented on pkg/virt-handler/isolation/isolation.go
> +	idx := 0
This does seems to be not used.

2023-05-02 19:29 UTC, matosatti commented on pkg/virt-handler/isolation/isolation.go
> +		fmt.Println(line)
Fixed

2023-05-02 19:29 UTC, matosatti commented on pkg/virt-handler/isolation/isolation.go
> +func (r *RealIsolationResult) GetQEMUKVMProcessPid() (int, error) {
Fixed

2023-05-02 19:35 UTC, matosatti commented
> Few nits inline

Luboslav,

Hopefully addressed all of your comments. Let me know if it looks OK now.

2023-05-03 06:43 UTC, xpivarc reviewed
You need to run `make generate` locally.

2023-05-03 06:43 UTC, xpivarc commented on pkg/virt-handler/isolation/isolation.go
> +func GetNspid(vmpid int, vmi *v1.VirtualMachineInstance) (int, error) {
Argument `vmi` is unused.

2023-05-03 06:43 UTC, xpivarc commented on pkg/virt-handler/isolation/isolation.go
> +func (r *RealIsolationResult) KvmPitPid(vmpid int, vmi *v1.VirtualMachineInstance) (int, error) {
You don't need `vmi` argument as it is unused in `GetNspid`.

2023-05-03 06:43 UTC, xpivarc commented on pkg/virt-handler/isolation/isolation.go
> +	KvmPitPid(vmpid int, vmi *v1.VirtualMachineInstance) (int, error)
What I meant is that the struct implementing this interface also needs to have `GetQEMUProcess` method. Meaning you can just call it within `KvmPitPId`

```
func (r *RealIsolationResult) KvmPitPid() (int, error) {
        vmpid, err := r.GetQEMUProcess()
        if err != nil {
           return err
         }
	processes, _ := ps.Processes()
	nspid, err := GetNspid(vmpid)
	if err != nil || nspid == -1 {
		return -1, err
	}
	pitstr := "kvm-pit/" + strconv.Itoa(nspid)

	for _, process := range processes {
		if process.Executable() == pitstr {
			return process.Pid(), nil
		}
	}
	return -1, nil
```

2023-05-04 13:03 UTC, matosatti commented
> You need to run `make generate` locally.

@xpivarc your comments should have been addressed, thanks!

2023-05-04 13:43 UTC, matosatti commented on pkg/virt-handler/isolation/isolation.go
> +	return 0, nil
If a process does not have "NSpid" field in its status file, yes it can.

2023-05-04 13:46 UTC, xpivarc approved these changes

2023-05-05 01:11 UTC, merged