virt-api: dialer should wrap ipv6 address with square brackets to portfoward ipv6 VM
kubevirt/kubevirt pull request #9851
Opened 2023-06-05 03:25 UTC by lxs137

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #9850 

**Special notes for your reviewer**:

**Release note**:

```release-note
virt-api: portfowrad can handle IPv6 VM
```

2023-06-05 05:46 UTC, orelmisan reviewed
Thank you for the PR @lxs137.

Could you please update the commit message to include more information about the problem this PR solves?

2023-06-05 05:47 UTC, orelmisan commented
/sig network

2023-06-05 06:11 UTC, lxs137 commented
> Thank you for the PR @lxs137.
> 
> Could you please update the commit message to include more information about the problem this PR solves?

@orelmisan I have updated the commit message :-)

2023-06-05 10:07 UTC, maiqueb requested changes
Can you add a unit test for this ? 

I honestly haven't looked at the surrounding code, thus I am unaware of how feasible / hard it is to create one.

2023-06-05 10:07 UTC, maiqueb commented on pkg/virt-api/rest/dialers.go
> +	}
I'd default to ipv4:

```golang
        addr := fmt.Sprintf("%s:%s", targetIP, port)
	if netutils.IsIPv6String(targetIP) {
		addr = fmt.Sprintf("[%s]:%s", targetIP, port)
	}
```

2023-06-05 10:14 UTC, orelmisan commented
@lxs137 In the network e2e tests there is a [comment](https://github.com/kubevirt/kubevirt/blob/2426905e43fa74ebbef528c456aa65107a926e73/tests/network/port_forward.go#L49) about port forwarding with IPv6 not being currently supported, with a link to a tracking [issue](https://github.com/kubevirt/kubevirt/issues/7276). 

I've asked @AlonaKaplan (the network maintainer) to take a look at this PR.

2023-06-05 13:46 UTC, maiqueb approved these changes
Perfect! 

Thanks for adding these neat unit tests. 

Nice contribution.

2023-06-06 01:29 UTC, lxs137 commented
/retest

2023-06-06 06:59 UTC, orelmisan commented
/ok-to-test

2023-06-07 01:44 UTC, lxs137 commented
/retest

2023-06-07 06:16 UTC, merged