virt-handler, network setup: Do not create podNIC for SR-IOV networks
kubevirt/kubevirt pull request #9890
Opened 2023-06-11 12:28 UTC by ormergi

**What this PR does / why we need it**:

Kubevirt expects SR-IOV interfaces to be set with userspace driver (vfio-pci) in order to attach them to VMs.
The interfaces are passthroughed to the VM using Libvirt API. 
Thus SR-IOV networks should not be part of the network setup.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This is a follow-up PR to resolve https://github.com/kubevirt/kubevirt/pull/9268#discussion_r1199753143

**Release note**:

```release-note

```

2023-06-11 13:44 UTC, ormergi commented
/test pull-kubevirt-unit-test

2023-06-11 14:19 UTC, ormergi commented
/cc @EdDev @orelmisan

2023-06-12 04:26 UTC, orelmisan requested changes
Thank you for the PR @ormergi.
Please consider creating a map of spec network names to spec interfaces (before iterating over the networks to create podNICs).

It will enable two improvements:
1. The lookup of interface by network name inside the loop will be in O(1) instead of O(N).
2. We could pass the interface to `newPhase1PodNIC` and later to `newPodNIC()` to eliminate the need to call `LookupInterfaceByName` [again](https://github.com/kubevirt/kubevirt/blob/0d30186ee2e6105ade46fc6f42718645aacc553a/pkg/network/setup/podnic.go#L112).

Edit: We could also apply this suggestion to `getPhase2NICs()`.

2023-06-13 06:29 UTC, ormergi commented
> Thank you for the PR @ormergi. Please consider creating a map of spec network names to spec interfaces (before iterating over the networks to create podNICs).
> 
> It will enable two improvements:
> 
>     1. The lookup of interface by network name inside the loop will be in O(1) instead of O(N).
> 
>     2. We could pass the interface to `newPhase1PodNIC` and later to `newPodNIC()` to eliminate the need to call `LookupInterfaceByName` [again](https://github.com/kubevirt/kubevirt/blob/0d30186ee2e6105ade46fc6f42718645aacc553a/pkg/network/setup/podnic.go#L112).
> 
> 
> Edit: We could also apply this suggestion to `getPhase2NICs()`.

Please note that such optimization around network/interfaces spec may end up neglectable because Kubevirt uses q35 machine type by default, which can have put to 31 PCI slots.
In terms of time complexity, where N is the VMI spec ifaces count, O(N) => O(32) => O(1).
Meaning it will always take the same time to tell which iface is SR-IOV iface, given max number of ifaces.

Regarding (1), its true that it will take O(1) to realize if an iface is SR-IOV at the podNIC creation loop, but it depends on a map that takes O(N) to build with additional O(N) in memory complexity.

2023-06-13 07:07 UTC, orelmisan approved these changes
Thank you @ormergi 

I will create a follow-up PR to pass the interface into `newPhase1PodNIC` and `newPhase2PodNIC`.

2023-06-15 07:14 UTC, merged

2023-06-19 11:46 UTC, AlonaKaplan commented
/cherry-pick release-1.0