[multi-arch] Use formatted archname in push-container-manifest
kubevirt/kubevirt pull request #9915
Opened 2023-06-14 15:59 UTC by fossedihelm

**What this PR does / why we need it**:
`bazel-push-images.sh` puts the digests files in paths based on the formatted arch names.
The same does not happen in `push-container-manifest.sh` which tries to find digests file using the plain arch names.
This results in a failure if you are building `aarch64` and `x86_64` together, as it happens for example in `automation/release.sh` Move the `format_archname` function to common.sh file, so that it can be also used by `push-container-manifest.sh`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #https://github.com/kubevirt/kubevirt/issues/9908

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/cc @rmohr @rthallisey @zhlhahaha @dhiller

2023-06-14 16:31 UTC, lyarwood commented
This looks valid but the eventual `podman manifest push` is still going to fail as I highlighted in https://github.com/kubevirt/kubevirt/issues/9908#issuecomment-1591272923. Can you also fix it here?

2023-06-15 04:18 UTC, zhlhahaha requested changes

2023-06-15 04:18 UTC, zhlhahaha commented on hack/push-container-manifest.sh
> +        ARCH=$(format_archname ARCH)
ARCH=$(format_archname $(ARCH))

2023-06-15 04:20 UTC, zhlhahaha commented
> This looks valid but the eventual `podman manifest push` is still going to fail as I highlighted in [#9908 (comment)](https://github.com/kubevirt/kubevirt/issues/9908#issuecomment-1591272923). Can you also fix it here?

Yes, it do have the issue. Beyond this, the pushing manifest script is for `docker` rather than `podman`. Here is the script for pushing manifest via `podman`, you may need to detect the contianer cli and then decide how to pushing manifest.
```
--- a/hack/push-container-manifest.sh
+++ b/hack/push-container-manifest.sh
@@ -29,14 +30,13 @@ fail_if_cri_bin_missing
 
 export DOCKER_CLI_EXPERIMENTAL=enabled
 for image in $(find ${DIGESTS_DIR}/*/bazel-bin/ -name '*.digest' -printf '%f\n' | sed s/^push-//g | sed s/\.digest$//g | sort -u); do
-    MANIFEST_IMAGES=""
+    echo ${KUBEVIRT_CRI} manifest create ${DOCKER_PREFIX}/${image}:${DOCKER_TAG} ${MANIFEST_IMAGES}
+    ${KUBEVIRT_CRI} manifest create ${DOCKER_PREFIX}/${image}:${DOCKER_TAG}
     for ARCH in ${BUILD_ARCH//,/ }; do
-        ARCH=$(format_archname ARCH)
+        ARCH=$(format_archname ${ARCH})
         digest=$(cat ${DIGESTS_DIR}/${ARCH}/bazel-bin/push-$image.digest)
-        MANIFEST_IMAGES="${MANIFEST_IMAGES} --amend ${DOCKER_PREFIX}/${image}@${digest}"
+        ${KUBEVIRT_CRI} manifest add ${DOCKER_PREFIX}/${image}:${DOCKER_TAG} ${DOCKER_PREFIX}/${image}@${digest}
     done
 
-    echo ${KUBEVIRT_CRI} manifest create ${DOCKER_PREFIX}/${image}:${DOCKER_TAG} ${MANIFEST_IMAGES}
-    ${KUBEVIRT_CRI} manifest create ${DOCKER_PREFIX}/${image}:${DOCKER_TAG} ${MANIFEST_IMAGES}
-    ${KUBEVIRT_CRI} manifest push ${DOCKER_PREFIX}/${image}:${DOCKER_TAG}
+    ${KUBEVIRT_CRI} manifest push --all ${DOCKER_PREFIX}/${image}:${DOCKER_TAG} ${DOCKER_PREFIX}/${image}:${DOCKER_TAG}
 done
```

2023-06-15 07:24 UTC, fossedihelm commented
@zhlhahaha Thanks for the script! @lyarwood Current implementation should cover both cases. Thank you!

2023-06-15 07:47 UTC, dhiller commented on hack/push-container-manifest.sh
> +        # Workaround https://github.com/containers/podman/issues/18360 and remove once https://github.com/containers/podman/commit/bab4217cd16be609ac35ccf3061d1e34f787856f is released
nit: add FIXME
```suggestion
        # FIXME: Workaround https://github.com/containers/podman/issues/18360 and remove once https://github.com/containers/podman/commit/bab4217cd16be609ac35ccf3061d1e34f787856f is released
```

2023-06-15 07:56 UTC, fossedihelm commented
> Found only two nits, you decide whether to address them. Comments inline.

Thanks @dhiller! Done

2023-06-15 07:57 UTC, dhiller approved these changes
/cherrypick release-1.0

/lgtm

2023-06-15 09:03 UTC, dhiller commented
/cherry-pick release-1.0

2023-06-16 10:53 UTC, merged